package accounting

import (
	"gorp/internal/field"
	"gorp/internal/model"
	"gorp/internal/registry"
)

func RegisterModels(reg *registry.Registry) error {
	for _, m := range Models() {
		if err := reg.RegisterModel(m); err != nil {
			return err
		}
	}
	return nil
}

func Models() []model.Model {
	return []model.Model{
		abstract("product.catalog.mixin",
			field.New("product_catalog_order_data", field.Text),
		),
		abstract("analytic.mixin",
			field.New("analytic_distribution", field.Json),
			field.New("distribution_analytic_account_ids", field.Many2Many).WithRelation("account.analytic.account"),
			field.New("analytic_precision", field.Int),
		),
		abstract("portal.mixin",
			field.New("access_url", field.Char),
			field.New("access_token", field.Char),
			field.New("access_warning", field.Text),
		),
		simple("digest.digest", "digest_digest",
			field.New("name", field.Char),
			field.New("active", field.Bool),
			field.New("company_id", field.Many2One).WithRelation("res.company"),
			field.New("currency_id", field.Many2One).WithRelation("res.currency"),
			field.New("periodicity", field.Selection),
			field.New("next_run_date", field.Date),
			field.New("user_ids", field.Many2Many).WithRelation("res.users"),
			field.New("state", field.Selection),
			field.New("kpi_account_total_revenue", field.Bool),
			field.New("kpi_account_total_revenue_value", field.Decimal),
		),
		simple("digest.tip", "digest_tip",
			field.New("name", field.Char),
			field.New("sequence", field.Int),
			field.New("group_id", field.Many2One).WithRelation("res.groups"),
			field.New("tip_description", field.Text),
		),
		simple("uom.category", "uom_category",
			field.New("name", field.Char),
		),
		simple("uom.uom", "uom_uom",
			field.New("name", field.Char),
			field.New("category_id", field.Many2One).WithRelation("uom.category"),
			field.New("uom_type", field.Selection),
			field.New("factor", field.Float),
			field.New("factor_inv", field.Float),
			field.New("rounding", field.Float),
			field.New("active", field.Bool),
		),
		simple("product.category", "product_category",
			field.New("name", field.Char),
			field.New("complete_name", field.Char),
			field.New("parent_id", field.Many2One).WithRelation("product.category"),
			field.New("child_id", field.One2Many).WithRelation("product.category").WithRelationField("parent_id"),
			field.New("parent_path", field.Char),
			field.New("product_count", field.Int),
			field.New("property_account_income_categ_id", field.Many2One).WithRelation("account.account"),
			field.New("property_account_expense_categ_id", field.Many2One).WithRelation("account.account"),
		),
		simple("product.tag", "product_tag",
			field.New("name", field.Char),
			field.New("color", field.Int),
		),
		simple("product.template", "product_template",
			field.New("name", field.Char),
			field.New("sequence", field.Int),
			field.New("description", field.Text),
			field.New("description_purchase", field.Text),
			field.New("description_sale", field.Text),
			field.New("type", field.Selection),
			field.New("detailed_type", field.Selection),
			field.New("categ_id", field.Many2One).WithRelation("product.category"),
			field.New("currency_id", field.Many2One).WithRelation("res.currency"),
			field.New("cost_currency_id", field.Many2One).WithRelation("res.currency"),
			field.New("list_price", field.Float),
			field.New("standard_price", field.Float),
			field.New("volume", field.Float),
			field.New("weight", field.Float),
			field.New("sale_ok", field.Bool),
			field.New("purchase_ok", field.Bool),
			field.New("uom_id", field.Many2One).WithRelation("uom.uom"),
			field.New("uom_ids", field.Many2Many).WithRelation("uom.uom"),
			field.New("uom_po_id", field.Many2One).WithRelation("uom.uom"),
			field.New("uom_name", field.Char),
			field.New("company_id", field.Many2One).WithRelation("res.company"),
			field.New("seller_ids", field.One2Many).WithRelation("product.supplierinfo").WithRelationField("product_tmpl_id"),
			field.New("active", field.Bool),
			field.New("color", field.Int),
			field.New("product_variant_ids", field.One2Many).WithRelation("product.product").WithRelationField("product_tmpl_id"),
			field.New("product_variant_id", field.Many2One).WithRelation("product.product"),
			field.New("product_variant_count", field.Int),
			field.New("barcode", field.Char),
			field.New("default_code", field.Char),
			field.New("is_favorite", field.Bool),
			field.New("product_tag_ids", field.Many2Many).WithRelation("product.tag"),
			field.New("taxes_id", field.Many2Many).WithRelation("account.tax"),
			field.New("tax_string", field.Char),
			field.New("supplier_taxes_id", field.Many2Many).WithRelation("account.tax"),
			field.New("property_account_income_id", field.Many2One).WithRelation("account.account"),
			field.New("property_account_expense_id", field.Many2One).WithRelation("account.account"),
			field.New("account_tag_ids", field.Many2Many).WithRelation("account.account.tag"),
			field.New("fiscal_country_codes", field.Char),
		),
		simple("product.product", "product_product",
			field.New("name", field.Char),
			field.New("product_tmpl_id", field.Many2One).WithRelation("product.template"),
			field.New("default_code", field.Char),
			field.New("barcode", field.Char),
			field.New("active", field.Bool),
			field.New("company_id", field.Many2One).WithRelation("res.company"),
			field.New("categ_id", field.Many2One).WithRelation("product.category"),
			field.New("uom_id", field.Many2One).WithRelation("uom.uom"),
			field.New("uom_po_id", field.Many2One).WithRelation("uom.uom"),
			field.New("lst_price", field.Float),
			field.New("standard_price", field.Float),
			field.New("taxes_id", field.Many2Many).WithRelation("account.tax"),
			field.New("supplier_taxes_id", field.Many2Many).WithRelation("account.tax"),
			field.New("tax_string", field.Char),
			field.New("display_name", field.Char),
		),
		simple("product.supplierinfo", "product_supplierinfo",
			field.New("name", field.Many2One).WithRelation("res.partner"),
			field.New("partner_id", field.Many2One).WithRelation("res.partner"),
			field.New("product_tmpl_id", field.Many2One).WithRelation("product.template"),
			field.New("product_id", field.Many2One).WithRelation("product.product"),
			field.New("company_id", field.Many2One).WithRelation("res.company"),
			field.New("sequence", field.Int),
			field.New("min_qty", field.Float),
			field.New("price", field.Float),
			field.New("currency_id", field.Many2One).WithRelation("res.currency"),
			field.New("delay", field.Int),
		),
		simple("product.pricelist", "product_pricelist",
			field.New("name", field.Char),
			field.New("active", field.Bool),
			field.New("currency_id", field.Many2One).WithRelation("res.currency"),
			field.New("company_id", field.Many2One).WithRelation("res.company"),
			field.New("item_ids", field.One2Many).WithRelation("product.pricelist.item").WithRelationField("pricelist_id"),
		),
		simple("product.pricelist.item", "product_pricelist_item",
			field.New("name", field.Char),
			field.New("pricelist_id", field.Many2One).WithRelation("product.pricelist"),
			field.New("product_tmpl_id", field.Many2One).WithRelation("product.template"),
			field.New("product_id", field.Many2One).WithRelation("product.product"),
			field.New("categ_id", field.Many2One).WithRelation("product.category"),
			field.New("applied_on", field.Selection),
			field.New("compute_price", field.Selection),
			field.New("fixed_price", field.Float),
			field.New("percent_price", field.Float),
		),
		simple("product.document", "product_document",
			field.New("name", field.Char),
			field.New("res_model", field.Char),
			field.New("res_id", field.Int),
			field.New("ir_attachment_id", field.Many2One).WithRelation("ir.attachment"),
			field.New("company_id", field.Many2One).WithRelation("res.company"),
		),
		simple("account.analytic.plan", "account_analytic_plan",
			field.New("name", field.Char),
			field.New("description", field.Text),
			field.New("active", field.Bool),
			field.New("sequence", field.Int),
			field.New("parent_id", field.Many2One).WithRelation("account.analytic.plan"),
			field.New("children_ids", field.One2Many).WithRelation("account.analytic.plan").WithRelationField("parent_id"),
			field.New("root_id", field.Many2One).WithRelation("account.analytic.plan"),
			field.New("default_applicability", field.Selection),
			field.New("applicability_ids", field.One2Many).WithRelation("account.analytic.applicability").WithRelationField("analytic_plan_id"),
			field.New("company_id", field.Many2One).WithRelation("res.company"),
		),
		simple("account.analytic.applicability", "account_analytic_applicability",
			field.New("analytic_plan_id", field.Many2One).WithRelation("account.analytic.plan"),
			field.New("business_domain", field.Selection),
			field.New("applicability", field.Selection),
			field.New("account_prefix", field.Char),
			field.New("product_categ_id", field.Many2One).WithRelation("product.category"),
			field.New("display_account_prefix", field.Bool),
			field.New("account_prefix_placeholder", field.Char),
			field.New("company_id", field.Many2One).WithRelation("res.company"),
		),
		simple("account.analytic.account", "account_analytic_account",
			field.New("name", field.Char),
			field.New("code", field.Char),
			field.New("active", field.Bool),
			field.New("partner_id", field.Many2One).WithRelation("res.partner"),
			field.New("company_id", field.Many2One).WithRelation("res.company"),
			field.New("currency_id", field.Many2One).WithRelation("res.currency"),
			field.New("plan_id", field.Many2One).WithRelation("account.analytic.plan"),
			field.New("root_plan_id", field.Many2One).WithRelation("account.analytic.plan"),
			field.New("line_ids", field.One2Many).WithRelation("account.analytic.line").WithRelationField("account_id"),
			field.New("debit", field.Decimal),
			field.New("credit", field.Decimal),
			field.New("balance", field.Decimal),
			field.New("invoice_count", field.Int),
			field.New("vendor_bill_count", field.Int),
		),
		simple("account.analytic.line", "account_analytic_line",
			field.New("name", field.Char),
			field.New("date", field.Date),
			field.New("account_id", field.Many2One).WithRelation("account.analytic.account"),
			field.New("auto_account_id", field.Many2One).WithRelation("account.analytic.account"),
			field.New("partner_id", field.Many2One).WithRelation("res.partner"),
			field.New("user_id", field.Many2One).WithRelation("res.users"),
			field.New("company_id", field.Many2One).WithRelation("res.company"),
			field.New("currency_id", field.Many2One).WithRelation("res.currency"),
			field.New("amount", field.Decimal),
			field.New("unit_amount", field.Float),
			field.New("product_id", field.Many2One).WithRelation("product.product"),
			field.New("product_uom_id", field.Many2One).WithRelation("uom.uom"),
			field.New("general_account_id", field.Many2One).WithRelation("account.account"),
			field.New("journal_id", field.Many2One).WithRelation("account.journal"),
			field.New("move_line_id", field.Many2One).WithRelation("account.move.line"),
			field.New("code", field.Char),
			field.New("ref", field.Char),
			field.New("category", field.Selection),
		),
		simple("account.analytic.distribution.model", "account_analytic_distribution_model",
			field.New("name", field.Char),
			field.New("sequence", field.Int),
			field.New("company_id", field.Many2One).WithRelation("res.company"),
			field.New("partner_id", field.Many2One).WithRelation("res.partner"),
			field.New("partner_category_id", field.Many2One),
			field.New("account_prefix", field.Char),
			field.New("account_id", field.Many2One).WithRelation("account.account"),
			field.New("product_id", field.Many2One).WithRelation("product.product"),
			field.New("product_categ_id", field.Many2One).WithRelation("product.category"),
			field.New("analytic_distribution", field.Json),
			field.New("analytic_precision", field.Int),
			field.New("prefix_placeholder", field.Char),
		),
		simple("onboarding.onboarding", "onboarding_onboarding",
			field.New("name", field.Char),
			field.New("route_name", field.Char),
			field.New("step_ids", field.Many2Many).WithRelation("onboarding.onboarding.step"),
			field.New("text_completed", field.Char),
			field.New("is_per_company", field.Bool),
			field.New("panel_close_action_name", field.Char),
			field.New("current_progress_id", field.Many2One).WithRelation("onboarding.progress"),
			field.New("current_onboarding_state", field.Selection),
			field.New("is_onboarding_closed", field.Bool),
			field.New("progress_ids", field.One2Many).WithRelation("onboarding.progress").WithRelationField("onboarding_id"),
			field.New("sequence", field.Int),
		),
		simple("onboarding.onboarding.step", "onboarding_onboarding_step",
			field.New("onboarding_ids", field.Many2Many).WithRelation("onboarding.onboarding"),
			field.New("title", field.Char),
			field.New("description", field.Char),
			field.New("button_text", field.Char),
			field.New("done_icon", field.Char),
			field.New("done_text", field.Char),
			field.New("step_image", field.Binary),
			field.New("step_image_filename", field.Char),
			field.New("step_image_alt", field.Char),
			field.New("panel_step_open_action_name", field.Char),
			field.New("current_progress_step_id", field.Many2One).WithRelation("onboarding.progress.step"),
			field.New("current_step_state", field.Selection),
			field.New("progress_ids", field.One2Many).WithRelation("onboarding.progress.step").WithRelationField("step_id"),
			field.New("is_per_company", field.Bool),
			field.New("sequence", field.Int),
		),
		simple("onboarding.progress", "onboarding_progress",
			field.New("onboarding_id", field.Many2One).WithRelation("onboarding.onboarding"),
			field.New("company_id", field.Many2One).WithRelation("res.company"),
			field.New("progress_step_ids", field.Many2Many).WithRelation("onboarding.progress.step"),
			field.New("onboarding_state", field.Selection),
			field.New("is_onboarding_closed", field.Bool),
		),
		simple("onboarding.progress.step", "onboarding_progress_step",
			field.New("step_id", field.Many2One).WithRelation("onboarding.onboarding.step"),
			field.New("progress_ids", field.Many2Many).WithRelation("onboarding.progress"),
			field.New("company_id", field.Many2One).WithRelation("res.company"),
			field.New("step_state", field.Selection),
		),
		transient("portal.wizard", "portal_wizard",
			field.New("partner_ids", field.Many2Many).WithRelation("res.partner"),
			field.New("user_ids", field.One2Many).WithRelation("portal.wizard.user").WithRelationField("wizard_id"),
			field.New("welcome_message", field.Text),
		),
		transient("portal.wizard.user", "portal_wizard_user",
			field.New("wizard_id", field.Many2One).WithRelation("portal.wizard"),
			field.New("partner_id", field.Many2One).WithRelation("res.partner"),
			field.New("email", field.Char),
			field.New("user_id", field.Many2One).WithRelation("res.users"),
			field.New("login_date", field.DateTime),
			field.New("is_portal", field.Bool),
			field.New("is_internal", field.Bool),
			field.New("email_state", field.Selection),
		),
		transient("portal.share", "portal_share",
			field.New("res_model", field.Char),
			field.New("res_id", field.Int),
			field.New("partner_ids", field.Many2Many).WithRelation("res.partner"),
			field.New("note", field.Text),
		),
		simple("account.account", "account_account",
			field.New("code", field.Char),
			field.New("placeholder_code", field.Char),
			field.New("name", field.Char),
			field.New("account_type", field.Selection),
			field.New("include_initial_balance", field.Bool),
			field.New("internal_group", field.Selection),
			field.New("root_id", field.Many2One).WithRelation("account.root"),
			field.New("group_id", field.Many2One).WithRelation("account.group"),
			field.New("company_id", field.Many2One).WithRelation("res.company"),
			field.New("currency_id", field.Many2One),
			field.New("reconcile", field.Bool),
			field.New("deprecated", field.Bool),
			field.New("non_trade", field.Bool),
			field.New("tax_ids", field.Many2Many).WithRelation("account.tax"),
			field.New("tag_ids", field.Many2Many).WithRelation("account.account.tag"),
		),
		simple("account.group", "account_group",
			field.New("parent_id", field.Many2One).WithRelation("account.group"),
			field.New("parent_path", field.Char),
			field.New("name", field.Char),
			field.New("code_prefix_start", field.Char),
			field.New("code_prefix_end", field.Char),
			field.New("company_id", field.Many2One).WithRelation("res.company"),
		),
		simple("account.root", "account_root",
			field.New("name", field.Char),
			field.New("parent_id", field.Many2One).WithRelation("account.root"),
		),
		simple("account.account.tag", "account_account_tag",
			field.New("name", field.Char),
			field.New("applicability", field.Selection),
			field.New("country_id", field.Many2One),
		),
		simple("account.account.type", "account_account_type",
			field.New("name", field.Char),
			field.New("type", field.Selection),
			field.New("include_initial_balance", field.Bool),
		),
		simple("account.bank.statement", "account_bank_statement",
			field.New("name", field.Char),
			field.New("journal_id", field.Many2One).WithRelation("account.journal"),
			field.New("company_id", field.Many2One).WithRelation("res.company"),
			field.New("balance_start", field.Decimal),
			field.New("balance_end_real", field.Decimal),
			field.New("state", field.Selection),
		),
		simple("account.bank.statement.line", "account_bank_statement_line",
			field.New("statement_id", field.Many2One).WithRelation("account.bank.statement"),
			field.New("journal_id", field.Many2One).WithRelation("account.journal"),
			field.New("move_id", field.Many2One).WithRelation("account.move"),
			field.New("company_id", field.Many2One).WithRelation("res.company"),
			field.New("payment_ref", field.Char),
			field.New("amount", field.Decimal),
			field.New("date", field.Date),
		),
		simple("account.cash.rounding", "account_cash_rounding",
			field.New("name", field.Char),
			field.New("rounding", field.Decimal),
			field.New("strategy", field.Selection),
			field.New("profit_account_id", field.Many2One).WithRelation("account.account"),
			field.New("loss_account_id", field.Many2One).WithRelation("account.account"),
		),
		simple("account.chart.template", "account_chart_template",
			field.New("name", field.Char),
			field.New("code_digits", field.Int),
			field.New("currency_id", field.Many2One),
			field.New("visible", field.Bool),
		),
		simple("account.code.mapping", "account_code_mapping",
			field.New("name", field.Char),
			field.New("company_id", field.Many2One).WithRelation("res.company"),
			field.New("account_id", field.Many2One).WithRelation("account.account"),
			field.New("code", field.Char),
		),
		simple("account.journal", "account_journal",
			field.New("name", field.Char),
			field.New("code", field.Char),
			field.New("type", field.Selection),
			field.New("company_id", field.Many2One).WithRelation("res.company"),
			field.New("currency_id", field.Many2One),
			field.New("default_account_id", field.Many2One).WithRelation("account.account"),
			field.New("active", field.Bool),
			field.New("sequence", field.Int),
			field.New("restrict_mode_hash_table", field.Bool),
			field.New("sequence_number_next", field.Int),
			field.New("refund_sequence", field.Bool),
		),
		simple("account.journal.group", "account_journal_group",
			field.New("name", field.Char),
			field.New("company_id", field.Many2One).WithRelation("res.company"),
			field.New("excluded_journal_ids", field.Many2Many).WithRelation("account.journal"),
			field.New("sequence", field.Int),
		),
		simple("account.incoterms", "account_incoterms",
			field.New("name", field.Char),
			field.New("code", field.Char),
			field.New("active", field.Bool),
		),
		simple("account.lock_exception", "account_lock_exception",
			field.New("active", field.Bool),
			field.New("state", field.Selection),
			field.New("company_id", field.Many2One).WithRelation("res.company"),
			field.New("user_id", field.Many2One).WithRelation("res.users"),
			field.New("reason", field.Text),
			field.New("end_datetime", field.DateTime),
			field.New("lock_date_field", field.Selection),
			field.New("lock_date", field.Date),
			field.New("company_lock_date", field.Date),
			field.New("fiscalyear_lock_date", field.Date),
			field.New("tax_lock_date", field.Date),
			field.New("sale_lock_date", field.Date),
			field.New("purchase_lock_date", field.Date),
		),
		simple("account.move", "account_move",
			field.New("name", field.Char),
			field.New("ref", field.Char),
			field.New("date", field.Date),
			field.New("invoice_date", field.Date),
			field.New("invoice_date_due", field.Date),
			field.New("state", field.Selection),
			field.New("move_type", field.Selection),
			field.New("journal_id", field.Many2One).WithRelation("account.journal"),
			field.New("company_id", field.Many2One).WithRelation("res.company"),
			field.New("currency_id", field.Many2One),
			field.New("partner_id", field.Many2One).WithRelation("res.partner"),
			field.New("fiscal_position_id", field.Many2One).WithRelation("account.fiscal.position"),
			field.New("amount_total", field.Decimal),
			field.New("amount_residual", field.Decimal),
			field.New("amount_residual_signed", field.Decimal),
			field.New("payment_state", field.Selection),
			field.New("status_in_payment", field.Selection),
			field.New("is_move_sent", field.Bool),
			field.New("sending_data", field.Text),
			field.New("is_being_sent", field.Bool),
			field.New("invoice_pdf_report_id", field.Many2One).WithRelation("ir.attachment"),
			field.New("invoice_pdf_report_file", field.Binary),
			field.New("ubl_cii_xml_file", field.Binary),
			field.New("message_main_attachment_id", field.Many2One).WithRelation("ir.attachment"),
			field.New("access_url", field.Char),
			field.New("access_token", field.Char),
			field.New("access_warning", field.Text),
			field.New("origin_payment_id", field.Many2One).WithRelation("account.payment"),
			field.New("statement_line_id", field.Many2One).WithRelation("account.bank.statement.line"),
			field.New("matched_payment_ids", field.Many2Many).WithRelation("account.payment"),
			field.New("reconciled_payment_ids", field.Many2Many).WithRelation("account.payment"),
			field.New("payment_count", field.Int),
			field.New("posted_before", field.Bool),
			field.New("inalterable_hash", field.Char),
			field.New("sequence_prefix", field.Char),
			field.New("sequence_number", field.Int),
			field.New("made_sequence_gap", field.Bool),
			field.New("secure_sequence_number", field.Int),
			field.New("auto_post", field.Selection),
			field.New("need_cancel_request", field.Bool),
			field.New("show_reset_to_draft_button", field.Bool),
			field.New("reversed_entry_id", field.Many2One).WithRelation("account.move"),
			field.New("reversal_move_ids", field.One2Many).WithRelation("account.move").WithRelationField("reversed_entry_id"),
			field.New("line_ids", field.One2Many).WithRelation("account.move.line"),
		),
		transient("account.move.reversal", "account_move_reversal",
			field.New("move_ids", field.Many2Many).WithRelation("account.move"),
			field.New("new_move_ids", field.Many2Many).WithRelation("account.move"),
			field.New("date", field.Date),
			field.New("reason", field.Char),
			field.New("journal_id", field.Many2One).WithRelation("account.journal"),
			field.New("company_id", field.Many2One).WithRelation("res.company"),
			field.New("available_journal_ids", field.Many2Many).WithRelation("account.journal"),
			field.New("country_code", field.Char),
			field.New("residual", field.Decimal),
			field.New("currency_id", field.Many2One),
			field.New("move_type", field.Char),
		),
		transient("account.payment.register", "account_payment_register",
			field.New("payment_date", field.Date),
			field.New("amount", field.Decimal),
			field.New("hide_writeoff_section", field.Bool),
			field.New("communication", field.Char),
			field.New("group_payment", field.Bool),
			field.New("early_payment_discount_mode", field.Bool),
			field.New("currency_id", field.Many2One),
			field.New("journal_id", field.Many2One).WithRelation("account.journal"),
			field.New("available_journal_ids", field.Many2Many).WithRelation("account.journal"),
			field.New("available_partner_bank_ids", field.Many2Many).WithRelation("res.partner.bank"),
			field.New("partner_bank_id", field.Many2One).WithRelation("res.partner.bank"),
			field.New("company_currency_id", field.Many2One),
			field.New("qr_code", field.Text),
			field.New("batches", field.Binary),
			field.New("installments_mode", field.Selection),
			field.New("installments_switch_html", field.Text),
			field.New("installments_switch_amount", field.Decimal),
			field.New("custom_user_amount", field.Decimal),
			field.New("custom_user_currency_id", field.Many2One),
			field.New("line_ids", field.Many2Many).WithRelation("account.move.line"),
			field.New("payment_type", field.Selection),
			field.New("partner_type", field.Selection),
			field.New("source_amount", field.Decimal),
			field.New("source_amount_currency", field.Decimal),
			field.New("source_currency_id", field.Many2One),
			field.New("can_edit_wizard", field.Bool),
			field.New("can_group_payments", field.Bool),
			field.New("company_id", field.Many2One).WithRelation("res.company"),
			field.New("partner_id", field.Many2One).WithRelation("res.partner"),
			field.New("payment_method_line_id", field.Many2One).WithRelation("account.payment.method.line"),
			field.New("available_payment_method_line_ids", field.Many2Many).WithRelation("account.payment.method.line"),
			field.New("payment_method_code", field.Char),
			field.New("payment_difference", field.Decimal),
			field.New("payment_difference_handling", field.Selection),
			field.New("writeoff_account_id", field.Many2One).WithRelation("account.account"),
			field.New("writeoff_label", field.Char),
			field.New("writeoff_is_exchange_account", field.Bool),
			field.New("show_payment_difference", field.Bool),
			field.New("show_partner_bank_account", field.Bool),
			field.New("require_partner_bank_account", field.Bool),
			field.New("country_code", field.Char),
			field.New("duplicate_payment_ids", field.Many2Many).WithRelation("account.payment"),
			field.New("is_register_payment_on_draft", field.Bool),
			field.New("actionable_errors", field.Text),
			field.New("untrusted_bank_ids", field.Many2Many).WithRelation("res.partner.bank"),
			field.New("total_payments_amount", field.Int),
			field.New("untrusted_payments_count", field.Int),
			field.New("missing_account_partners", field.Many2Many).WithRelation("res.partner"),
		),
		transient("account.move.send.wizard", "account_move_send_wizard",
			field.New("move_id", field.Many2One).WithRelation("account.move"),
			field.New("company_id", field.Many2One).WithRelation("res.company"),
			field.New("alerts", field.Text),
			field.New("sending_methods", field.Text),
			field.New("sending_method_checkboxes", field.Text),
			field.New("display_attachments_widget", field.Bool),
			field.New("extra_edis", field.Text),
			field.New("extra_edi_checkboxes", field.Text),
			field.New("invoice_edi_format", field.Selection),
			field.New("pdf_report_id", field.Many2One).WithRelation("ir.actions.report"),
			field.New("available_pdf_report_ids", field.Many2Many).WithRelation("ir.actions.report"),
			field.New("display_pdf_report_id", field.Bool),
			field.New("template_id", field.Many2One).WithRelation("mail.template"),
			field.New("lang", field.Char),
			field.New("mail_partner_ids", field.Many2Many).WithRelation("res.partner"),
			field.New("mail_attachments_widget", field.Text),
			field.New("attachments_not_supported", field.Text),
			field.New("model", field.Char),
			field.New("res_ids", field.Text),
			field.New("template_name", field.Char),
			field.New("subject", field.Char),
			field.New("body", field.Text),
			field.New("render_model", field.Char),
			field.New("can_edit_body", field.Bool),
		),
		transient("account.move.send.batch.wizard", "account_move_send_batch_wizard",
			field.New("move_ids", field.Many2Many).WithRelation("account.move"),
			field.New("summary_data", field.Text),
			field.New("alerts", field.Text),
		),
		simple("account.move.line", "account_move_line",
			field.New("move_id", field.Many2One).WithRelation("account.move"),
			field.New("account_id", field.Many2One).WithRelation("account.account"),
			field.New("account_type", field.Selection),
			field.New("account_internal_group", field.Selection),
			field.New("partner_id", field.Many2One).WithRelation("res.partner"),
			field.New("company_id", field.Many2One).WithRelation("res.company"),
			field.New("currency_id", field.Many2One),
			field.New("name", field.Char),
			field.New("parent_state", field.Selection),
			field.New("move_type", field.Selection),
			field.New("journal_id", field.Many2One).WithRelation("account.journal"),
			field.New("debit", field.Decimal),
			field.New("credit", field.Decimal),
			field.New("balance", field.Decimal),
			field.New("quantity", field.Float),
			field.New("price_unit", field.Decimal),
			field.New("price_subtotal", field.Decimal),
			field.New("price_total", field.Decimal),
			field.New("discount", field.Float),
			field.New("display_type", field.Selection),
			field.New("date_maturity", field.Date),
			field.New("product_id", field.Many2One).WithRelation("product.product"),
			field.New("product_uom_id", field.Many2One).WithRelation("uom.uom"),
			field.New("allowed_uom_ids", field.Many2Many).WithRelation("uom.uom"),
			field.New("product_category_id", field.Many2One).WithRelation("product.category"),
			field.New("analytic_line_ids", field.One2Many).WithRelation("account.analytic.line").WithRelationField("move_line_id"),
			field.New("analytic_distribution", field.Json),
			field.New("distribution_analytic_account_ids", field.Many2Many).WithRelation("account.analytic.account"),
			field.New("analytic_precision", field.Int),
			field.New("has_invalid_analytics", field.Bool),
			field.New("amount_currency", field.Decimal),
			field.New("amount_residual", field.Decimal),
			field.New("amount_residual_currency", field.Decimal),
			field.New("reconciled", field.Bool),
			field.New("payment_id", field.Many2One).WithRelation("account.payment"),
			field.New("full_reconcile_id", field.Many2One).WithRelation("account.full.reconcile"),
			field.New("matched_debit_ids", field.One2Many).WithRelation("account.partial.reconcile").WithRelationField("credit_move_id"),
			field.New("matched_credit_ids", field.One2Many).WithRelation("account.partial.reconcile").WithRelationField("debit_move_id"),
			field.New("tax_ids", field.Many2Many).WithRelation("account.tax"),
			field.New("tax_tag_ids", field.Many2Many).WithRelation("account.account.tag"),
			field.New("tax_line_id", field.Many2One).WithRelation("account.tax"),
			field.New("tax_repartition_line_id", field.Many2One).WithRelation("account.tax.repartition.line"),
		),
		simple("account.payment", "account_payment",
			field.New("name", field.Char),
			field.New("payment_type", field.Selection),
			field.New("partner_type", field.Selection),
			field.New("partner_id", field.Many2One).WithRelation("res.partner"),
			field.New("amount", field.Decimal),
			field.New("company_id", field.Many2One).WithRelation("res.company"),
			field.New("currency_id", field.Many2One),
			field.New("journal_id", field.Many2One).WithRelation("account.journal"),
			field.New("move_id", field.Many2One).WithRelation("account.move"),
			field.New("state", field.Selection),
			field.New("is_reconciled", field.Bool),
			field.New("is_matched", field.Bool),
			field.New("is_sent", field.Bool),
			field.New("invoice_ids", field.Many2Many).WithRelation("account.move"),
			field.New("reconciled_invoice_ids", field.Many2Many).WithRelation("account.move"),
			field.New("reconciled_bill_ids", field.Many2Many).WithRelation("account.move"),
			field.New("need_cancel_request", field.Bool),
		),
		simple("account.payment.method", "account_payment_method",
			field.New("name", field.Char),
			field.New("code", field.Char),
			field.New("payment_type", field.Selection),
		),
		simple("account.payment.method.line", "account_payment_method_line",
			field.New("name", field.Char),
			field.New("journal_id", field.Many2One).WithRelation("account.journal"),
			field.New("payment_method_id", field.Many2One).WithRelation("account.payment.method"),
			field.New("payment_account_id", field.Many2One).WithRelation("account.account"),
		),
		simple("account.payment.term", "account_payment_term",
			field.New("name", field.Char),
			field.New("company_id", field.Many2One).WithRelation("res.company"),
			field.New("active", field.Bool),
			field.New("note", field.Text),
			field.New("line_ids", field.One2Many).WithRelation("account.payment.term.line"),
		),
		simple("account.payment.term.line", "account_payment_term_line",
			field.New("payment_id", field.Many2One).WithRelation("account.payment.term"),
			field.New("value", field.Selection),
			field.New("value_amount", field.Decimal),
			field.New("nb_days", field.Int),
		),
		simple("account.tax", "account_tax",
			field.New("name", field.Char),
			field.New("description", field.Char),
			field.New("invoice_label", field.Char),
			field.New("amount_type", field.Selection),
			field.New("amount", field.Decimal),
			field.New("type_tax_use", field.Selection),
			field.New("company_id", field.Many2One).WithRelation("res.company"),
			field.New("tax_group_id", field.Many2One).WithRelation("account.tax.group"),
			field.New("repartition_line_ids", field.One2Many).WithRelation("account.tax.repartition.line"),
			field.New("fiscal_position_ids", field.Many2Many).WithRelation("account.fiscal.position"),
			field.New("original_tax_ids", field.Many2Many).WithRelation("account.tax"),
			field.New("children_tax_ids", field.Many2Many).WithRelation("account.tax"),
			field.New("is_domestic", field.Bool),
			field.New("active", field.Bool),
		),
		simple("account.tax.group", "account_tax_group",
			field.New("name", field.Char),
			field.New("country_id", field.Many2One).WithRelation("res.country"),
			field.New("tax_payable_account_id", field.Many2One).WithRelation("account.account"),
			field.New("tax_receivable_account_id", field.Many2One).WithRelation("account.account"),
			field.New("company_id", field.Many2One).WithRelation("res.company"),
			field.New("sequence", field.Int),
		),
		simple("account.tax.repartition.line", "account_tax_repartition_line",
			field.New("tax_id", field.Many2One).WithRelation("account.tax"),
			field.New("company_id", field.Many2One).WithRelation("res.company"),
			field.New("document_type", field.Selection),
			field.New("repartition_type", field.Selection),
			field.New("factor_percent", field.Decimal),
			field.New("account_id", field.Many2One).WithRelation("account.account"),
			field.New("tag_ids", field.Many2Many).WithRelation("account.account.tag"),
			field.New("sequence", field.Int),
		),
		simple("account.fiscal.position", "account_fiscal_position",
			field.New("name", field.Char),
			field.New("company_id", field.Many2One).WithRelation("res.company"),
			field.New("auto_apply", field.Bool),
			field.New("country_id", field.Many2One).WithRelation("res.country"),
			field.New("sequence", field.Int),
			field.New("account_ids", field.One2Many).WithRelation("account.fiscal.position.account").WithRelationField("position_id"),
			field.New("tax_ids", field.Many2Many).WithRelation("account.tax"),
		),
		simple("account.fiscal.position.account", "account_fiscal_position_account",
			field.New("position_id", field.Many2One).WithRelation("account.fiscal.position"),
			field.New("company_id", field.Many2One).WithRelation("res.company"),
			field.New("account_src_id", field.Many2One).WithRelation("account.account"),
			field.New("account_dest_id", field.Many2One).WithRelation("account.account"),
		),
		abstract("account.document.import.mixin"),
		simple("account.partial.reconcile", "account_partial_reconcile",
			field.New("debit_move_id", field.Many2One).WithRelation("account.move.line"),
			field.New("credit_move_id", field.Many2One).WithRelation("account.move.line"),
			field.New("amount", field.Decimal),
			field.New("debit_amount_currency", field.Decimal),
			field.New("credit_amount_currency", field.Decimal),
			field.New("full_reconcile_id", field.Many2One).WithRelation("account.full.reconcile"),
			field.New("company_id", field.Many2One).WithRelation("res.company"),
		),
		simple("account.full.reconcile", "account_full_reconcile",
			field.New("name", field.Char),
			field.New("partial_reconcile_ids", field.One2Many).WithRelation("account.partial.reconcile"),
		),
		simple("account.reconcile.model", "account_reconcile_model",
			field.New("name", field.Char),
			field.New("sequence", field.Int),
			field.New("rule_type", field.Selection),
			field.New("company_id", field.Many2One).WithRelation("res.company"),
			field.New("line_ids", field.One2Many).WithRelation("account.reconcile.model.line"),
		),
		simple("account.reconcile.model.line", "account_reconcile_model_line",
			field.New("model_id", field.Many2One).WithRelation("account.reconcile.model"),
			field.New("account_id", field.Many2One).WithRelation("account.account"),
			field.New("company_id", field.Many2One).WithRelation("res.company"),
			field.New("amount_type", field.Selection),
			field.New("amount", field.Decimal),
		),
		simple("account.report", "account_report",
			field.New("name", field.Char),
			field.New("root_report_id", field.Many2One).WithRelation("account.report"),
			field.New("country_id", field.Many2One),
			field.New("line_ids", field.One2Many).WithRelation("account.report.line").WithRelationField("report_id"),
			field.New("column_ids", field.One2Many).WithRelation("account.report.column").WithRelationField("report_id"),
		),
		simple("account.report.line", "account_report_line",
			field.New("name", field.Char),
			field.New("code", field.Char),
			field.New("report_id", field.Many2One).WithRelation("account.report"),
			field.New("parent_id", field.Many2One).WithRelation("account.report.line"),
			field.New("children_ids", field.One2Many).WithRelation("account.report.line").WithRelationField("parent_id"),
			field.New("expression_ids", field.One2Many).WithRelation("account.report.expression").WithRelationField("report_line_id"),
		),
		simple("account.report.expression", "account_report_expression",
			field.New("label", field.Char),
			field.New("engine", field.Selection),
			field.New("formula", field.Text),
			field.New("report_line_id", field.Many2One).WithRelation("account.report.line"),
		),
		simple("account.report.column", "account_report_column",
			field.New("name", field.Char),
			field.New("expression_label", field.Char),
			field.New("figure_type", field.Selection),
			field.New("report_id", field.Many2One).WithRelation("account.report"),
		),
		simple("account.report.external.value", "account_report_external_value",
			field.New("name", field.Char),
			field.New("target_report_expression_id", field.Many2One).WithRelation("account.report.expression"),
			field.New("company_id", field.Many2One).WithRelation("res.company"),
			field.New("date", field.Date),
			field.New("value", field.Decimal),
		),
		simple("account.invoice.report", "account_invoice_report",
			field.New("move_id", field.Many2One).WithRelation("account.move"),
			field.New("journal_id", field.Many2One).WithRelation("account.journal"),
			field.New("company_id", field.Many2One).WithRelation("res.company"),
			field.New("company_currency_id", field.Many2One).WithRelation("res.currency"),
			field.New("partner_id", field.Many2One).WithRelation("res.partner"),
			field.New("commercial_partner_id", field.Many2One).WithRelation("res.partner"),
			field.New("country_id", field.Many2One).WithRelation("res.country"),
			field.New("invoice_user_id", field.Many2One).WithRelation("res.users"),
			field.New("move_type", field.Selection),
			field.New("state", field.Selection),
			field.New("payment_state", field.Selection),
			field.New("fiscal_position_id", field.Many2One).WithRelation("account.fiscal.position"),
			field.New("invoice_date", field.Date),
			field.New("quantity", field.Float),
			field.New("product_id", field.Many2One).WithRelation("product.product"),
			field.New("product_uom_id", field.Many2One).WithRelation("uom.uom"),
			field.New("product_categ_id", field.Many2One).WithRelation("product.category"),
			field.New("invoice_date_due", field.Date),
			field.New("account_id", field.Many2One).WithRelation("account.account"),
			field.New("price_subtotal_currency", field.Decimal),
			field.New("price_subtotal", field.Decimal),
			field.New("price_total", field.Decimal),
			field.New("price_total_currency", field.Decimal),
			field.New("price_average", field.Decimal),
			field.New("price_margin", field.Decimal),
			field.New("inventory_value", field.Decimal),
			field.New("currency_id", field.Many2One).WithRelation("res.currency"),
		),
		transient("account.automatic.entry.wizard", "account_automatic_entry_wizard",
			field.New("action", field.Selection),
			field.New("move_data", field.Text),
			field.New("preview_move_data", field.Text),
			field.New("move_line_ids", field.Many2Many).WithRelation("account.move.line"),
			field.New("date", field.Date),
			field.New("company_id", field.Many2One).WithRelation("res.company"),
			field.New("company_currency_id", field.Many2One).WithRelation("res.currency"),
			field.New("percentage", field.Float),
			field.New("total_amount", field.Decimal),
			field.New("journal_id", field.Many2One).WithRelation("account.journal"),
			field.New("account_type", field.Selection),
			field.New("expense_accrual_account", field.Many2One).WithRelation("account.account"),
			field.New("revenue_accrual_account", field.Many2One).WithRelation("account.account"),
			field.New("lock_date_message", field.Text),
			field.New("destination_account_id", field.Many2One).WithRelation("account.account"),
			field.New("display_currency_helper", field.Bool),
		),
		transient("account.autopost.bills.wizard", "account_autopost_bills_wizard",
			field.New("partner_id", field.Many2One).WithRelation("res.partner"),
			field.New("partner_name", field.Char),
			field.New("nb_unmodified_bills", field.Int),
		),
		transient("account.resequence.wizard", "account_resequence_wizard",
			field.New("sequence_number_reset", field.Selection),
			field.New("first_date", field.Date),
			field.New("end_date", field.Date),
			field.New("first_name", field.Char),
			field.New("ordering", field.Selection),
			field.New("move_ids", field.Many2Many).WithRelation("account.move"),
			field.New("new_values", field.Text),
			field.New("preview_moves", field.Text),
		),
		transient("account.secure.entries.wizard", "account_secure_entries_wizard",
			field.New("company_id", field.Many2One).WithRelation("res.company"),
			field.New("country_code", field.Char),
			field.New("hash_date", field.Date),
			field.New("chains_to_hash_with_gaps", field.Text),
			field.New("max_hash_date", field.Date),
			field.New("unreconciled_bank_statement_line_ids", field.Many2Many).WithRelation("account.bank.statement.line"),
			field.New("not_hashable_unlocked_move_ids", field.Many2Many).WithRelation("account.move"),
			field.New("move_to_hash_ids", field.Many2Many).WithRelation("account.move"),
			field.New("warnings", field.Text),
		),
		transient("account.merge.wizard", "account_merge_wizard",
			field.New("account_ids", field.Many2Many).WithRelation("account.account"),
			field.New("is_group_by_name", field.Bool),
			field.New("wizard_line_ids", field.One2Many).WithRelation("account.merge.wizard.line").WithRelationField("wizard_id"),
			field.New("disable_merge_button", field.Bool),
		),
		transient("account.merge.wizard.line", "account_merge_wizard_line",
			field.New("wizard_id", field.Many2One).WithRelation("account.merge.wizard"),
			field.New("grouping_key", field.Char),
			field.New("sequence", field.Int),
			field.New("display_type", field.Selection),
			field.New("is_selected", field.Bool),
			field.New("account_id", field.Many2One).WithRelation("account.account"),
			field.New("company_ids", field.Many2Many).WithRelation("res.company"),
			field.New("info", field.Text),
			field.New("account_has_hashed_entries", field.Bool),
		),
		transient("account.accrued.orders.wizard", "account_accrued_orders_wizard",
			field.New("company_id", field.Many2One).WithRelation("res.company"),
			field.New("journal_id", field.Many2One).WithRelation("account.journal"),
			field.New("date", field.Date),
			field.New("reversal_date", field.Date),
			field.New("amount", field.Decimal),
			field.New("currency_id", field.Many2One).WithRelation("res.currency"),
			field.New("account_id", field.Many2One).WithRelation("account.account"),
			field.New("preview_data", field.Text),
			field.New("display_amount", field.Bool),
		),
	}
}

func simple(name, table string, fields ...field.Field) model.Model {
	m := model.New(name, table)
	for _, f := range fields {
		m.AddField(f)
	}
	return m
}

func transient(name, table string, fields ...field.Field) model.Model {
	m := simple(name, table, fields...)
	m.Transient = true
	return m
}

func abstract(name string, fields ...field.Field) model.Model {
	m := model.New(name, "")
	m.Abstract = true
	for _, f := range fields {
		m.AddField(f)
	}
	return m
}
