package base

import (
	"gorp/internal/field"
	"gorp/internal/model"
	"gorp/internal/module"
	"gorp/internal/registry"
)

func Manifest() module.Manifest {
	return module.Manifest{
		Name:          "Base",
		TechnicalName: "base",
		Version:       "19.0.1.0.0",
		Category:      "Hidden",
		Installable:   true,
		Data: []string{
			"data/res_bank.xml",
			"data/res.lang.csv",
			"data/res_lang_data.xml",
			"data/res_currency_data.xml",
			"data/res_country_data.xml",
			"data/res.country.state.csv",
			"data/base_data.xml",
			"data/technical_views.xml",
			"data/technical_menus.xml",
			"data/res_partner_data.xml",
			"data/res_company_data.xml",
			"data/report_paperformat_data.xml",
			"data/mail_message_subtype_data.xml",
			"data/mail_compose_views.xml",
			"data/ir_cron_data.xml",
			"data/ir_actions_server_data.xml",
			"data/res_users_data.xml",
			"security/base_groups.xml",
			"security/base_security.xml",
			"security/ir.model.access.csv",
		},
	}
}

func RegisterModels(reg *registry.Registry) error {
	for _, m := range Models() {
		if err := reg.RegisterModel(m); err != nil {
			return err
		}
	}
	return nil
}

func Models() []model.Model {
	return []model.Model{
		simple("ir.module.module", "ir_module_module", field.New("name", field.Char), field.New("state", field.Selection)),
		simple("ir.module.module.dependency", "ir_module_module_dependency", field.New("name", field.Char), field.New("module_id", field.Many2One).WithRelation("ir.module.module"), field.New("auto_install_required", field.Bool)),
		simple("ir.module.module.exclusion", "ir_module_module_exclusion", field.New("name", field.Char), field.New("module_id", field.Many2One).WithRelation("ir.module.module")),
		simple("ir.module.category",
			"ir_module_category",
			field.New("name", field.Char),
			field.New("parent_id", field.Many2One).WithRelation("ir.module.category"),
			field.New("child_ids", field.One2Many).WithRelation("ir.module.category").WithRelationField("parent_id"),
			field.New("module_ids", field.One2Many).WithRelation("ir.module.module").WithRelationField("category_id"),
			field.New("privilege_ids", field.One2Many).WithRelation("res.groups.privilege").WithRelationField("category_id"),
			field.New("description", field.Text),
			field.New("sequence", field.Int),
			field.New("visible", field.Bool),
			field.New("exclusive", field.Bool),
			field.New("xml_id", field.Char),
		),
		simple("ir.model", "ir_model", field.New("model", field.Char), field.New("name", field.Char), field.New("abstract", field.Bool), field.New("transient", field.Bool), field.New("is_mail_thread", field.Bool), field.New("is_mail_activity", field.Bool), field.New("is_mail_blacklist", field.Bool)),
		simple("ir.model.constraint", "ir_model_constraint", field.New("name", field.Char), field.New("model", field.Many2One).WithRelation("ir.model"), field.New("type", field.Selection), field.New("definition", field.Text)),
		simple("ir.model.relation", "ir_model_relation", field.New("name", field.Char), field.New("model", field.Many2One).WithRelation("ir.model")),
		simple("ir.model.inherit", "ir_model_inherit", field.New("name", field.Char), field.New("model_id", field.Many2One).WithRelation("ir.model")),
		simple("ir.model.access",
			"ir_model_access",
			field.New("name", field.Char),
			field.New("active", field.Bool),
			field.New("model", field.Char),
			field.New("model_id", field.Many2One).WithRelation("ir.model"),
			field.New("group_id", field.Many2One).WithRelation("res.groups"),
			field.New("perm_read", field.Bool),
			field.New("perm_write", field.Bool),
			field.New("perm_create", field.Bool),
			field.New("perm_unlink", field.Bool),
		),
		simple("ir.model.fields", "ir_model_fields", field.New("model", field.Char), field.New("name", field.Char), field.New("ttype", field.Selection), field.New("relation", field.Char), field.New("relation_field", field.Char), field.New("groups", field.Text), field.New("ai_vector_size", field.Int)),
		simple("ir.model.fields.selection", "ir_model_fields_selection", field.New("name", field.Char), field.New("field_id", field.Many2One).WithRelation("ir.model.fields"), field.New("value", field.Char), field.New("sequence", field.Int)),
		simple("ir.rule",
			"ir_rule",
			field.New("name", field.Char),
			field.New("model", field.Char),
			field.New("model_id", field.Many2One).WithRelation("ir.model"),
			field.New("domain", field.Text),
			field.New("domain_force", field.Text),
			field.New("groups", field.Many2Many).WithRelation("res.groups"),
			field.New("group_ids", field.Text),
			field.New("global", field.Bool),
			field.New("active", field.Bool),
			field.New("perm_read", field.Bool),
			field.New("perm_write", field.Bool),
			field.New("perm_create", field.Bool),
			field.New("perm_unlink", field.Bool),
		),
		simple("ir.model.data",
			"ir_model_data",
			field.New("module", field.Char),
			field.New("name", field.Char),
			field.New("complete_name", field.Char),
			field.New("model", field.Char),
			field.New("res_id", field.Int),
			field.New("noupdate", field.Bool),
		),
		simple("ir.sequence",
			"ir_sequence",
			field.New("name", field.Char),
			field.New("code", field.Char),
			field.New("prefix", field.Char),
			field.New("suffix", field.Char),
			field.New("padding", field.Int),
			field.New("number_next", field.Int),
			field.New("number_next_actual", field.Int),
			field.New("number_increment", field.Int),
			field.New("company_id", field.Many2One).WithRelation("res.company"),
			field.New("active", field.Bool),
			field.New("implementation", field.Selection),
			field.New("use_date_range", field.Bool),
			field.New("date_range_ids", field.One2Many).WithRelation("ir.sequence.date_range").WithRelationField("sequence_id"),
		),
		simple("ir.sequence.date_range",
			"ir_sequence_date_range",
			field.New("date_from", field.Date),
			field.New("date_to", field.Date),
			field.New("sequence_id", field.Many2One).WithRelation("ir.sequence"),
			field.New("number_next", field.Int),
			field.New("number_next_actual", field.Int),
		),
		simple("decimal.precision", "decimal_precision", field.New("name", field.Char), field.New("digits", field.Int)),
		simple("ir.config_parameter", "ir_config_parameter", field.New("key", field.Char), field.New("value", field.Text)),
		simple("ir.default", "ir_default", field.New("model", field.Char), field.New("field", field.Char), field.New("value", field.Text)),
		simple("res.config", "res_config", field.New("name", field.Char)),
		resConfigSettingsModel(),
		simple("ir.cron",
			"ir_cron",
			field.New("name", field.Char),
			field.New("ir_actions_server_id", field.Many2One).WithRelation("ir.actions.server"),
			field.New("cron_name", field.Char),
			field.New("active", field.Bool),
			field.New("group_ids", field.Many2Many).WithRelation("res.groups"),
			field.New("interval_number", field.Int),
			field.New("interval_type", field.Selection),
			field.New("nextcall", field.DateTime),
			field.New("lastcall", field.DateTime),
			field.New("user_id", field.Many2One).WithRelation("res.users"),
			field.New("model_id", field.Many2One).WithRelation("ir.model"),
			field.New("state", field.Selection),
			field.New("code", field.Text),
			field.New("priority", field.Int),
			field.New("failure_count", field.Int),
			field.New("first_failure_date", field.DateTime),
			field.New("action_name", field.Char),
		),
		simple("ir.cron.trigger", "ir_cron_trigger", field.New("cron_id", field.Many2One).WithRelation("ir.cron"), field.New("call_at", field.DateTime)),
		simple("ir.cron.progress",
			"ir_cron_progress",
			field.New("cron_id", field.Many2One).WithRelation("ir.cron"),
			field.New("done", field.Int),
			field.New("remaining", field.Int),
			field.New("deactivate", field.Bool),
			field.New("timed_out_counter", field.Int),
			field.New("started_at", field.DateTime),
			field.New("updated_at", field.DateTime),
		),
		simple("base.automation", "base_automation",
			field.New("name", field.Char),
			field.New("description", field.Text),
			field.New("model_id", field.Many2One).WithRelation("ir.model"),
			field.New("model_name", field.Char),
			field.New("model_is_mail_thread", field.Bool),
			field.New("action_server_id", field.Many2One).WithRelation("ir.actions.server"),
			field.New("action_server_ids", field.One2Many).WithRelation("ir.actions.server").WithRelationField("base_automation_id"),
			field.New("url", field.Char),
			field.New("webhook_uuid", field.Char),
			field.New("record_getter", field.Char),
			field.New("log_webhook_calls", field.Bool),
			field.New("active", field.Bool),
			field.New("trigger", field.Selection),
			field.New("trg_selection_field_id", field.Many2One).WithRelation("ir.model.fields.selection"),
			field.New("trg_field_ref_model_name", field.Char),
			field.New("trg_field_ref", field.Char),
			field.New("trg_date_id", field.Many2One).WithRelation("ir.model.fields"),
			field.New("trg_date_range", field.Int),
			field.New("trg_date_range_mode", field.Selection),
			field.New("trg_date_range_type", field.Selection),
			field.New("trg_date_calendar_id", field.Many2One).WithRelation("resource.calendar"),
			field.New("filter_pre_domain", field.Text),
			field.New("previous_domain", field.Text),
			field.New("filter_domain", field.Text),
			field.New("last_run", field.DateTime),
			field.New("on_change_field_ids", field.Many2Many).WithRelation("ir.model.fields"),
			field.New("trigger_field_ids", field.Many2Many).WithRelation("ir.model.fields"),
			field.New("trigger_field_names", field.Text),
		),
		simple("res.users",
			"res_users",
			field.New("login", field.Char),
			field.New("password", field.Char),
			field.New("email", field.Char),
			field.New("name", field.Char),
			field.New("active", field.Bool),
			field.New("active_partner", field.Bool),
			field.New("login_date", field.DateTime),
			field.New("company_id", field.Many2One).WithRelation("res.company"),
			field.New("company_ids", field.Many2Many).WithRelation("res.company"),
			field.New("groups_id", field.Many2Many).WithRelation("res.groups"),
			field.New("group_ids", field.Many2Many).WithRelation("res.groups"),
			field.New("all_group_ids", field.Many2Many).WithRelation("res.groups"),
			field.New("accesses_count", field.Int),
			field.New("rules_count", field.Int),
			field.New("groups_count", field.Int),
			field.New("view_group_hierarchy", field.Json),
			field.New("role", field.Selection),
			field.New("partner_id", field.Many2One).WithRelation("res.partner"),
			field.New("commercial_partner_id", field.Many2One).WithRelation("res.partner"),
			field.New("share", field.Bool),
			field.New("signature", field.Text),
			field.New("image_1920", field.Binary),
			field.New("notification_type", field.Selection),
			field.New("outgoing_mail_server_id", field.Many2One).WithRelation("ir.mail_server"),
			field.New("outgoing_mail_server_type", field.Selection),
			field.New("has_external_mail_server", field.Bool),
		),
		simple("res.groups",
			"res_groups",
			field.New("name", field.Char),
			field.New("full_name", field.Char),
			field.New("share", field.Bool),
			field.New("sequence", field.Int),
			field.New("category_id", field.Many2One).WithRelation("ir.module.category"),
			field.New("privilege_id", field.Many2One).WithRelation("res.groups.privilege"),
			field.New("implied_ids", field.Many2Many).WithRelation("res.groups"),
			field.New("all_implied_ids", field.Many2Many).WithRelation("res.groups"),
			field.New("implied_by_ids", field.Many2Many).WithRelation("res.groups"),
			field.New("all_implied_by_ids", field.Many2Many).WithRelation("res.groups"),
			field.New("disjoint_ids", field.Many2Many).WithRelation("res.groups"),
			field.New("user_ids", field.Many2Many).WithRelation("res.users"),
			field.New("all_user_ids", field.Many2Many).WithRelation("res.users"),
			field.New("all_users_count", field.Int),
			field.New("model_access", field.One2Many).WithRelation("ir.model.access").WithRelationField("group_id"),
			field.New("rule_groups", field.Many2Many).WithRelation("ir.rule"),
			field.New("menu_access", field.Many2Many).WithRelation("ir.ui.menu"),
			field.New("view_access", field.Many2Many).WithRelation("ir.ui.view"),
			field.New("comment", field.Text),
			field.New("api_key_duration", field.Float),
			field.New("view_group_hierarchy", field.Json),
		),
		simple("res.company",
			"res_company",
			field.New("name", field.Char),
			field.New("active", field.Bool),
			field.New("parent_id", field.Many2One).WithRelation("res.company"),
			field.New("currency_id", field.Many2One).WithRelation("res.currency"),
			field.New("country_id", field.Many2One).WithRelation("res.country"),
			field.New("partner_id", field.Many2One).WithRelation("res.partner"),
			field.New("fiscalyear_lock_date", field.Date),
			field.New("tax_lock_date", field.Date),
			field.New("sale_lock_date", field.Date),
			field.New("purchase_lock_date", field.Date),
			field.New("hard_lock_date", field.Date),
			field.New("user_fiscalyear_lock_date", field.Date),
			field.New("user_tax_lock_date", field.Date),
			field.New("user_sale_lock_date", field.Date),
			field.New("user_purchase_lock_date", field.Date),
			field.New("user_hard_lock_date", field.Date),
			field.New("restrictive_audit_trail", field.Bool),
			field.New("alias_domain_id", field.Many2One).WithRelation("mail.alias.domain"),
		),
		simple("resource.calendar",
			"resource_calendar",
			field.New("name", field.Char),
			field.New("active", field.Bool),
			field.New("company_id", field.Many2One).WithRelation("res.company"),
			field.New("attendance_ids", field.One2Many).WithRelation("resource.calendar.attendance").WithRelationField("calendar_id"),
			field.New("leave_ids", field.One2Many).WithRelation("resource.calendar.leaves").WithRelationField("calendar_id"),
			field.New("global_leave_ids", field.One2Many).WithRelation("resource.calendar.leaves").WithRelationField("calendar_id"),
			field.New("schedule_type", field.Selection),
			field.New("duration_based", field.Bool),
			field.New("flexible_hours", field.Bool),
			field.New("full_time_required_hours", field.Float),
			field.New("hours_per_day", field.Float),
			field.New("hours_per_week", field.Float),
			field.New("two_weeks_calendar", field.Bool),
			field.New("tz", field.Selection),
		),
		simple("resource.calendar.attendance",
			"resource_calendar_attendance",
			field.New("name", field.Char),
			field.New("dayofweek", field.Selection),
			field.New("hour_from", field.Float),
			field.New("hour_to", field.Float),
			field.New("duration_hours", field.Float),
			field.New("duration_days", field.Float),
			field.New("calendar_id", field.Many2One).WithRelation("resource.calendar"),
			field.New("duration_based", field.Bool),
			field.New("day_period", field.Selection),
			field.New("week_type", field.Selection),
			field.New("two_weeks_calendar", field.Bool),
			field.New("display_type", field.Selection),
			field.New("sequence", field.Int),
		),
		simple("resource.calendar.leaves",
			"resource_calendar_leaves",
			field.New("name", field.Char),
			field.New("company_id", field.Many2One).WithRelation("res.company"),
			field.New("calendar_id", field.Many2One).WithRelation("resource.calendar"),
			field.New("date_from", field.DateTime),
			field.New("date_to", field.DateTime),
			field.New("resource_id", field.Many2One).WithRelation("resource.resource"),
			field.New("time_type", field.Selection),
		),
		simple("resource.resource",
			"resource_resource",
			field.New("name", field.Char),
			field.New("active", field.Bool),
			field.New("company_id", field.Many2One).WithRelation("res.company"),
			field.New("resource_type", field.Selection),
			field.New("user_id", field.Many2One).WithRelation("res.users"),
			field.New("time_efficiency", field.Float),
			field.New("calendar_id", field.Many2One).WithRelation("resource.calendar"),
			field.New("tz", field.Selection),
		),
		withInherit(simple("res.partner",
			"res_partner",
			field.New("name", field.Char).WithDefaultExportCompatible(),
			field.New("active", field.Bool),
			field.New("email", field.Char),
			field.New("email_normalized", field.Char),
			field.New("message_bounce", field.Int),
			field.New("phone", field.Char),
			field.New("phone_sanitized", field.Char),
			field.New("phone_blacklisted", field.Bool),
			field.New("street", field.Char),
			field.New("city", field.Char),
			field.New("zip", field.Char),
			field.New("country_id", field.Many2One).WithRelation("res.country"),
			field.New("state_id", field.Many2One).WithRelation("res.country.state"),
			field.New("company_id", field.Many2One).WithRelation("res.company"),
			field.New("parent_id", field.Many2One).WithRelation("res.partner"),
			field.New("commercial_partner_id", field.Many2One).WithRelation("res.partner"),
			field.New("partner_share", field.Bool),
			field.New("is_company", field.Bool),
			field.New("image_1920", field.Binary),
			field.New("signup_type", field.Char),
			field.New("agent_ids", field.One2Many).WithRelation("ai.agent"),
		), "mail.thread", "mail.activity.mixin"),
		simple("res.partner.industry",
			"res_partner_industry",
			field.New("name", field.Char),
			field.New("full_name", field.Char),
		),
		simple("res.country",
			"res_country",
			field.New("name", field.Char),
			field.New("code", field.Char),
			field.New("address_format", field.Text),
			field.New("currency_id", field.Many2One).WithRelation("res.currency"),
			field.New("phone_code", field.Int),
			field.New("vat_label", field.Char),
			field.New("state_required", field.Bool),
			field.New("zip_required", field.Bool),
			field.New("name_position", field.Selection),
			field.New("state_ids", field.One2Many).WithRelation("res.country.state"),
			field.New("active", field.Bool),
		),
		simple("res.country.group",
			"res_country_group",
			field.New("name", field.Char),
			field.New("code", field.Char),
			field.New("country_ids", field.Many2Many).WithRelation("res.country"),
		),
		simple("res.country.state",
			"res_country_state",
			field.New("name", field.Char),
			field.New("code", field.Char),
			field.New("country_id", field.Many2One).WithRelation("res.country"),
		),
		simple("res.currency",
			"res_currency",
			field.New("name", field.Char),
			field.New("symbol", field.Char),
			field.New("position", field.Selection),
			field.New("rounding", field.Float),
			field.New("decimal_places", field.Int),
			field.New("iso_numeric", field.Char),
			field.New("full_name", field.Char),
			field.New("currency_unit_label", field.Char),
			field.New("currency_subunit_label", field.Char),
			field.New("active", field.Bool),
		),
		simple("res.lang",
			"res_lang",
			field.New("name", field.Char),
			field.New("code", field.Char),
			field.New("iso_code", field.Char),
			field.New("url_code", field.Char),
			field.New("direction", field.Selection),
			field.New("grouping", field.Char),
			field.New("decimal_point", field.Char),
			field.New("thousands_sep", field.Char),
			field.New("date_format", field.Char),
			field.New("time_format", field.Char),
			field.New("week_start", field.Char),
			field.New("flag_image", field.Binary),
			field.New("active", field.Bool),
		),
		simple("res.bank", "res_bank", field.New("name", field.Char), field.New("bic", field.Char), field.New("active", field.Bool), field.New("country", field.Many2One).WithRelation("res.country")),
		simple("res.partner.bank", "res_partner_bank", field.New("acc_number", field.Char), field.New("partner_id", field.Many2One).WithRelation("res.partner"), field.New("bank_id", field.Many2One).WithRelation("res.bank"), field.New("company_id", field.Many2One).WithRelation("res.company"), field.New("active", field.Bool)),
		simple("res.partner.category", "res_partner_category", field.New("name", field.Char), field.New("parent_id", field.Many2One).WithRelation("res.partner.category")),
		simple("res.groups.privilege", "res_groups_privilege", field.New("name", field.Char), field.New("description", field.Text), field.New("placeholder", field.Char), field.New("sequence", field.Int), field.New("category_id", field.Many2One).WithRelation("ir.module.category"), field.New("group_ids", field.One2Many).WithRelation("res.groups").WithRelationField("privilege_id")),
		simple("res.users.settings", "res_users_settings", field.New("user_id", field.Many2One).WithRelation("res.users"), field.New("is_discuss_sidebar_category_channel_open", field.Bool), field.New("is_discuss_sidebar_category_chat_open", field.Bool)),
		simple("res.users.apikeys", "res_users_apikeys", field.New("name", field.Char), field.New("user_id", field.Many2One).WithRelation("res.users"), field.New("scope", field.Char), field.New("key", field.Char), field.New("create_date", field.DateTime)),
		simple("res.users.apikeys.description", "res_users_apikeys_description", field.New("name", field.Char), field.New("user_id", field.Many2One).WithRelation("res.users")),
		simple("res.users.apikeys.show", "res_users_apikeys_show", field.New("name", field.Char), field.New("user_id", field.Many2One).WithRelation("res.users")),
		simple("res.users.deletion", "res_users_deletion", field.New("user_id", field.Many2One).WithRelation("res.users")),
		simple("res.users.log", "res_users_log", field.New("create_uid", field.Many2One).WithRelation("res.users"), field.New("create_date", field.DateTime)),
		simple("res.users.identitycheck", "res_users_identitycheck", field.New("create_uid", field.Many2One).WithRelation("res.users"), field.New("user_id", field.Many2One).WithRelation("res.users"), field.New("request", field.Char).WithGroups(".")),
		simple("change.password.wizard", "change_password_wizard", field.New("user_ids", field.Many2Many).WithRelation("res.users")),
		simple("change.password.user", "change_password_user", field.New("create_uid", field.Many2One).WithRelation("res.users"), field.New("user_id", field.Many2One).WithRelation("res.users"), field.New("new_passwd", field.Char)),
		simple("change.password.own", "change_password_own", field.New("create_uid", field.Many2One).WithRelation("res.users"), field.New("user_id", field.Many2One).WithRelation("res.users"), field.New("new_passwd", field.Char)),
		simple("res.device", "res_device", field.New("name", field.Char), field.New("user_id", field.Many2One).WithRelation("res.users")),
		simple("res.device.log", "res_device_log", field.New("device_id", field.Many2One).WithRelation("res.device"), field.New("user_id", field.Many2One).WithRelation("res.users")),
		simple("res.currency.rate", "res_currency_rate", field.New("name", field.Date), field.New("currency_id", field.Many2One).WithRelation("res.currency"), field.New("company_id", field.Many2One).WithRelation("res.company"), field.New("rate", field.Float)),
		simple("ir.ui.view.custom", "ir_ui_view_custom", field.New("user_id", field.Many2One).WithRelation("res.users"), field.New("ref_id", field.Many2One).WithRelation("ir.ui.view"), field.New("arch", field.Text)),
		simple("properties.base.definition", "properties_base_definition", field.New("name", field.Char)),
		simple("base.enable.profiling.wizard", "base_enable_profiling_wizard", field.New("duration", field.Int)),
		simple("base.language.export", "base_language_export", field.New("name", field.Char)),
		simple("base.language.import", "base_language_import", field.New("name", field.Char)),
		simple("base.language.install", "base_language_install", field.New("lang", field.Char)),
		simple("base.module.update", "base_module_update", field.New("updated", field.Int), field.New("added", field.Int), field.New("state", field.Selection)),
		simple("base.module.upgrade", "base_module_upgrade", field.New("module_info", field.Text)),
		simple("base.module.uninstall", "base_module_uninstall", field.New("module_id", field.Many2One).WithRelation("ir.module.module")),
		simple("base.partner.merge.automatic.wizard", "base_partner_merge_automatic_wizard", field.New("partner_ids", field.Many2Many).WithRelation("res.partner")),
		simple("base.partner.merge.line", "base_partner_merge_line", field.New("wizard_id", field.Many2One).WithRelation("base.partner.merge.automatic.wizard"), field.New("partner_id", field.Many2One).WithRelation("res.partner")),
		simple("wizard.ir.model.menu.create", "wizard_ir_model_menu_create", field.New("model_id", field.Many2One).WithRelation("ir.model"), field.New("menu_name", field.Char)),
		simple("reset.view.arch.wizard", "reset_view_arch_wizard", field.New("view_id", field.Many2One).WithRelation("ir.ui.view")),
		simple("report.layout", "report_layout", field.New("name", field.Char), field.New("view_id", field.Many2One).WithRelation("ir.ui.view")),
		simple("ir.demo", "ir_demo", field.New("name", field.Char)),
		simple("ir.demo.failure", "ir_demo_failure", field.New("name", field.Char)),
		simple("ir.demo.failure.wizard", "ir_demo_failure_wizard", field.New("failure_id", field.Many2One).WithRelation("ir.demo.failure")),
		simple("ir.exports", "ir_exports", field.New("name", field.Char), field.New("resource", field.Char), field.New("export_fields", field.One2Many).WithRelation("ir.exports.line").WithRelationField("export_id")),
		simple("ir.exports.line", "ir_exports_line", field.New("name", field.Char), field.New("export_id", field.Many2One).WithRelation("ir.exports")),
		simple("ir.logging", "ir_logging", field.New("name", field.Char), field.New("type", field.Selection), field.New("level", field.Char), field.New("message", field.Text)),
		simple("ir.mail_server", "ir_mail_server", field.New("name", field.Char), field.New("active", field.Bool), field.New("smtp_host", field.Char), field.New("smtp_port", field.Int), field.New("smtp_encryption", field.Selection), field.New("smtp_authentication", field.Selection), field.New("from_filter", field.Char), field.New("sequence", field.Int), field.New("smtp_debug", field.Bool), field.New("max_email_size", field.Int), field.New("smtp_user", field.Char).WithGroups("base.group_system"), field.New("smtp_pass", field.Char).WithGroups("base.group_system"), field.New("smtp_ssl_certificate", field.Binary).WithGroups("base.group_system"), field.New("smtp_ssl_private_key", field.Binary).WithGroups("base.group_system"), field.New("owner_user_id", field.Many2One).WithRelation("res.users"), field.New("owner_limit_time", field.DateTime), field.New("owner_limit_count", field.Int)),
		simple("ir.profile", "ir_profile", field.New("name", field.Char), field.New("session", field.Char), field.New("duration", field.Float)),
		simple("digest.digest", "digest_digest", field.New("name", field.Char), field.New("active", field.Bool), field.New("company_id", field.Many2One).WithRelation("res.company"), field.New("currency_id", field.Many2One).WithRelation("res.currency"), field.New("periodicity", field.Selection), field.New("next_run_date", field.Date), field.New("user_ids", field.Many2Many).WithRelation("res.users"), field.New("available_fields", field.Char), field.New("is_subscribed", field.Bool), field.New("state", field.Selection), field.New("kpi_res_users_connected", field.Bool), field.New("kpi_res_users_connected_value", field.Int), field.New("kpi_mail_message_total", field.Bool), field.New("kpi_mail_message_total_value", field.Int), field.New("kpi_account_total_revenue", field.Bool), field.New("kpi_account_total_revenue_value", field.Decimal)),
		simple("digest.tip", "digest_tip", field.New("name", field.Char), field.New("sequence", field.Int), field.New("group_id", field.Many2One).WithRelation("res.groups"), field.New("user_ids", field.Many2Many).WithRelation("res.users"), field.New("tip_description", field.Text)),
		simple("ir.attachment", "ir_attachment", field.New("name", field.Char), field.New("res_model", field.Char), field.New("res_field", field.Char), field.New("res_id", field.Int), field.New("company_id", field.Many2One).WithRelation("res.company"), field.New("type", field.Selection), field.New("url", field.Char), field.New("mimetype", field.Char), field.New("datas", field.Binary), field.New("file_size", field.Int), field.New("public", field.Bool), field.New("access_token", field.Char).WithGroups("base.group_user"), field.New("checksum", field.Char), field.New("has_thumbnail", field.Bool)),
		simple("ir.filters", "ir_filters", field.New("name", field.Char), field.New("model_id", field.Char), field.New("domain", field.Text), field.New("context", field.Text), field.New("sort", field.Text), field.New("user_id", field.Many2One).WithRelation("res.users"), field.New("action_id", field.Many2One), field.New("embedded_action_id", field.Many2One).WithRelation("ir.embedded.actions"), field.New("is_default", field.Bool), field.New("active", field.Bool)),
		simple("ir.ui.view",
			"ir_ui_view",
			field.New("name", field.Char),
			field.New("model", field.Char),
			field.New("type", field.Selection),
			field.New("arch", field.Text),
			field.New("key", field.Char),
			field.New("inherit_id", field.Many2One).WithRelation("ir.ui.view"),
			field.New("inherit_id_ref", field.Char),
			field.New("mode", field.Selection),
			field.New("priority", field.Int),
			field.New("active", field.Bool),
			field.New("groups_id", field.Many2Many).WithRelation("res.groups"),
			field.New("primary", field.Bool),
			field.New("customize_show", field.Bool),
			field.New("track", field.Bool),
			field.New("page", field.Bool),
			field.New("website_id", field.Many2One),
		),
		simple("ir.asset",
			"ir_asset",
			field.New("name", field.Char),
			field.New("active", field.Bool),
			field.New("bundle", field.Char),
			field.New("directive", field.Selection),
			field.New("path", field.Char),
			field.New("target", field.Char),
			field.New("sequence", field.Int),
		),
		simple("ir.ui.menu",
			"ir_ui_menu",
			field.New("name", field.Char),
			field.New("active", field.Bool),
			field.New("parent_id", field.Many2One).WithRelation("ir.ui.menu"),
			field.New("action", field.Char),
			field.New("sequence", field.Int),
			field.New("groups_id", field.Many2Many).WithRelation("res.groups"),
			field.New("web_icon", field.Char),
			field.New("web_icon_data", field.Text),
			field.New("web_icon_data_mimetype", field.Char),
		),
		simple("ir.actions.actions",
			"ir_actions",
			field.New("name", field.Char),
			field.New("type", field.Char),
			field.New("xml_id", field.Char),
			field.New("help", field.Text),
			field.New("path", field.Char),
			field.New("binding_model_id", field.Many2One).WithRelation("ir.model"),
			field.New("binding_type", field.Selection),
			field.New("binding_view_types", field.Char),
		),
		simple("ir.actions.act_window",
			"ir_act_window",
			field.New("name", field.Char),
			field.New("type", field.Char),
			field.New("res_model", field.Char),
			field.New("res_id", field.Int),
			field.New("view_mode", field.Char),
			field.New("views", field.Binary),
			field.New("embedded_action_ids", field.One2Many).WithRelation("ir.embedded.actions").WithRelationField("parent_action_id"),
			field.New("close_on_report_download", field.Bool),
			field.New("mobile_view_mode", field.Char),
			field.New("view_id", field.Many2One).WithRelation("ir.ui.view"),
			field.New("search_view_id", field.Many2One).WithRelation("ir.ui.view"),
			field.New("domain", field.Text),
			field.New("context", field.Text),
			field.New("target", field.Selection),
			field.New("limit", field.Int),
			field.New("help", field.Text),
			field.New("path", field.Char),
			field.New("usage", field.Char),
			field.New("filter", field.Bool),
			field.New("cache", field.Bool),
			field.New("group_ids", field.Many2Many).WithRelation("res.groups"),
			field.New("binding_model_id", field.Many2One).WithRelation("ir.model"),
			field.New("binding_type", field.Selection),
			field.New("binding_view_types", field.Char),
		),
		simple("ir.actions.act_window.view", "ir_act_window_view", field.New("sequence", field.Int), field.New("view_mode", field.Char), field.New("view_id", field.Many2One).WithRelation("ir.ui.view"), field.New("act_window_id", field.Many2One).WithRelation("ir.actions.act_window"), field.New("multi", field.Bool)),
		simple("ir.actions.act_window_close", "ir_actions", field.New("name", field.Char), field.New("type", field.Char), field.New("effect", field.Json), field.New("infos", field.Json)),
		simple("ir.actions.act_url", "ir_act_url", field.New("name", field.Char), field.New("type", field.Char), field.New("url", field.Char), field.New("target", field.Selection), field.New("close", field.Bool), field.New("binding_model_id", field.Many2One).WithRelation("ir.model"), field.New("binding_type", field.Selection), field.New("binding_view_types", field.Char)),
		simple("ir.actions.todo", "ir_actions_todo", field.New("name", field.Char), field.New("action_id", field.Many2One), field.New("state", field.Selection), field.New("sequence", field.Int)),
		simple("ir.actions.server",
			"ir_act_server",
			field.New("name", field.Char),
			field.New("type", field.Char),
			field.New("model_id", field.Many2One).WithRelation("ir.model"),
			field.New("binding_model_id", field.Many2One).WithRelation("ir.model"),
			field.New("binding_type", field.Selection),
			field.New("binding_view_types", field.Char),
			field.New("model_name", field.Char),
			field.New("automated_name", field.Char),
			field.New("allowed_states", field.Json),
			field.New("available_model_ids", field.Many2Many).WithRelation("ir.model"),
			serverActionStateField(),
			field.New("active", field.Bool),
			field.New("usage", field.Selection),
			field.New("sequence", field.Int),
			field.New("base_automation_id", field.Many2One).WithRelation("base.automation"),
			field.New("go_action_name", field.Char),
			field.New("ir_cron_ids", field.One2Many).WithRelation("ir.cron").WithRelationField("ir_actions_server_id"),
			field.New("values", field.Text),
			field.New("value", field.Text),
			field.New("html_value", field.Text),
			field.New("evaluation_type", field.Selection),
			field.New("sequence_id", field.Many2One).WithRelation("ir.sequence"),
			field.New("resource_ref", field.Char),
			field.New("selection_value", field.Many2One).WithRelation("ir.model.fields.selection"),
			field.New("parent_id", field.Many2One).WithRelation("ir.actions.server"),
			field.New("child_ids", field.One2Many).WithRelation("ir.actions.server").WithRelationField("parent_id"),
			field.New("crud_model_id", field.Many2One).WithRelation("ir.model"),
			field.New("crud_model_name", field.Char),
			field.New("link_field_id", field.Many2One).WithRelation("ir.model.fields"),
			field.New("group_ids", field.Many2Many).WithRelation("res.groups"),
			field.New("update_field_id", field.Many2One).WithRelation("ir.model.fields"),
			field.New("update_path", field.Char),
			field.New("update_related_model_id", field.Many2One).WithRelation("ir.model"),
			field.New("update_field_type", field.Selection),
			field.New("update_m2m_operation", field.Selection),
			field.New("update_boolean_value", field.Selection),
			field.New("warning", field.Text),
			field.New("show_code_history", field.Bool),
			field.New("value_field_to_show", field.Selection),
			field.New("mail_template_id", field.Many2One).WithRelation("mail.template"),
			field.New("template_id", field.Many2One).WithRelation("mail.template"),
			field.New("mail_post_autofollow", field.Bool),
			field.New("mail_post_method", field.Selection),
			field.New("followers_type", field.Selection),
			field.New("followers_partner_field_name", field.Char),
			field.New("partner_ids", field.Many2Many).WithRelation("res.partner"),
			field.New("activity_type_id", field.Many2One).WithRelation("mail.activity.type"),
			field.New("activity_summary", field.Char),
			field.New("activity_note", field.Text),
			field.New("activity_date_deadline_range", field.Int),
			field.New("activity_date_deadline_range_type", field.Selection),
			field.New("activity_user_type", field.Selection),
			field.New("activity_user_id", field.Many2One).WithRelation("res.users"),
			field.New("activity_user_field_name", field.Char),
			field.New("sms_template_id", field.Many2One).WithRelation("sms.template"),
			field.New("sms_method", field.Selection),
			field.New("wa_template_id", field.Many2One).WithRelation("whatsapp.template"),
			field.New("documents_account_create_model", field.Selection),
			field.New("documents_account_journal_id", field.Many2One).WithRelation("account.journal"),
			field.New("documents_account_suitable_journal_ids", field.Many2Many).WithRelation("account.journal"),
			field.New("documents_account_move_type", field.Char),
			field.New("queue_key", field.Char),
			field.New("webhook_url", field.Char),
			field.New("webhook_field_ids", field.Many2Many).WithRelation("ir.model.fields"),
			field.New("webhook_sample_payload", field.Text),
			field.New("code", field.Text).WithGroups("base.group_system"),
			field.New("ai_tool_ids", field.Many2Many).WithRelation("ir.actions.server"),
			field.New("ai_action_prompt", field.Text),
			field.New("ai_tool_show_warning", field.Bool),
			field.New("ai_tool_description", field.Text),
			field.New("ai_tool_schema", field.Text),
			field.New("use_in_ai", field.Bool),
			field.New("ai_tool_allow_end_message", field.Bool),
			field.New("ai_tool_is_candidate", field.Bool),
			field.New("ai_tool_has_schema", field.Bool),
		),
		simple("ir.actions.server.history", "ir_actions_server_history", field.New("action_id", field.Many2One).WithRelation("ir.actions.server"), field.New("code", field.Text), field.New("create_uid", field.Many2One).WithRelation("res.users"), field.New("create_date", field.DateTime)),
		serverActionHistoryWizardModel(),
		simple("ir.actions.client", "ir_act_client", field.New("name", field.Char), field.New("type", field.Char), field.New("tag", field.Char), field.New("res_model", field.Char), field.New("target", field.Selection), field.New("context", field.Text), field.New("params", field.Json), field.New("params_store", field.Binary)),
		simple("ir.actions.report",
			"ir_act_report_xml",
			field.New("name", field.Char),
			field.New("type", field.Char),
			field.New("model", field.Char),
			field.New("model_id", field.Many2One).WithRelation("ir.model"),
			field.New("report_name", field.Char),
			field.New("report_type", field.Selection),
			field.New("target", field.Selection),
			field.New("context", field.Text),
			field.New("data", field.Json),
			field.New("close_on_report_download", field.Bool),
			field.New("report_file", field.Char),
			field.New("print_report_name", field.Char),
			field.New("attachment", field.Char),
			field.New("attachment_use", field.Bool),
			field.New("multi", field.Bool),
			field.New("binding_model_id", field.Many2One).WithRelation("ir.model"),
			field.New("binding_type", field.Selection),
			field.New("binding_view_types", field.Char),
			field.New("paperformat_id", field.Many2One).WithRelation("report.paperformat"),
			field.New("groups_id", field.Many2Many).WithRelation("res.groups"),
			field.New("domain", field.Text),
			field.New("is_invoice_report", field.Bool),
		),
		embeddedActionsModel(),
		reportPaperformatModel(),
		abstract("mail.thread", field.New("message_ids", field.One2Many).WithRelation("mail.message"), field.New("message_follower_ids", field.One2Many).WithRelation("mail.followers")),
		abstract("mail.activity.mixin", field.New("activity_ids", field.One2Many).WithRelation("mail.activity")),
		withLogAccess(simple("mail.message", "mail_message", field.New("subject", field.Char), field.New("body", field.Text), field.New("message_type", field.Selection), field.New("model", field.Char), field.New("res_id", field.Int), field.New("record_alias_domain_id", field.Many2One).WithRelation("mail.alias.domain"), field.New("record_company_id", field.Many2One).WithRelation("res.company"), field.New("author_id", field.Many2One).WithRelation("res.partner"), field.New("author_guest_id", field.Many2One).WithRelation("mail.guest"), field.New("email_from", field.Char), field.New("message_id", field.Char), field.New("incoming_email_to", field.Text), field.New("incoming_email_cc", field.Char), field.New("outgoing_email_to", field.Char), field.New("reply_to", field.Char), field.New("reply_to_force_new", field.Bool), field.New("mail_server_id", field.Many2One).WithRelation("ir.mail_server"), field.New("email_layout_xmlid", field.Char), field.New("email_add_signature", field.Bool), field.New("date", field.DateTime), field.New("parent_id", field.Many2One).WithRelation("mail.message"), field.New("subtype_id", field.Many2One).WithRelation("mail.message.subtype"), field.New("mail_activity_type_id", field.Many2One).WithRelation("mail.activity.type"), field.New("partner_ids", field.Many2Many).WithRelation("res.partner"), field.New("attachment_ids", field.Many2Many).WithRelation("ir.attachment"), field.New("body_is_html", field.Bool), field.New("is_internal", field.Bool), field.New("reaction_ids", field.One2Many).WithRelation("mail.message.reaction").WithRelationField("message_id"), field.New("starred", field.Bool), field.New("starred_partner_ids", field.Many2Many).WithRelation("res.partner"), field.New("tracking_value_ids", field.One2Many).WithRelation("mail.tracking.value").WithRelationField("mail_message_id"))),
		withLogAccess(simple("mail.inbound.message.lock", "mail_inbound_message_lock", field.New("message_id", field.Char))),
		simple("mail.tracking.value", "mail_tracking_value",
			field.New("field_id", field.Many2One).WithRelation("ir.model.fields"),
			field.New("field_info", field.Text),
			field.New("field_name", field.Char),
			field.New("field_desc", field.Char),
			field.New("field_type", field.Selection),
			field.New("old_value_integer", field.Int),
			field.New("old_value_float", field.Float),
			field.New("old_value_char", field.Char),
			field.New("old_value_text", field.Text),
			field.New("old_value_datetime", field.DateTime),
			field.New("new_value_integer", field.Int),
			field.New("new_value_float", field.Float),
			field.New("new_value_char", field.Char),
			field.New("new_value_text", field.Text),
			field.New("new_value_datetime", field.DateTime),
			field.New("currency_id", field.Many2One).WithRelation("res.currency"),
			field.New("mail_message_id", field.Many2One).WithRelation("mail.message"),
		),
		simple("mail.message.reaction", "mail_message_reaction", field.New("message_id", field.Many2One).WithRelation("mail.message"), field.New("content", field.Char), field.New("partner_id", field.Many2One).WithRelation("res.partner"), field.New("guest_id", field.Many2One).WithRelation("mail.guest")),
		withLogAccess(simple("mail.mail", "mail_mail", field.New("mail_message_id", field.Many2One).WithRelation("mail.message"), field.New("recipient_ids", field.Many2Many).WithRelation("res.partner"), field.New("attachment_ids", field.Many2Many).WithRelation("ir.attachment"), field.New("mail_server_id", field.Many2One).WithRelation("ir.mail_server"), field.New("record_alias_domain_id", field.Many2One).WithRelation("mail.alias.domain"), field.New("record_company_id", field.Many2One).WithRelation("res.company"), field.New("author_id", field.Many2One).WithRelation("res.partner"), field.New("email_from", field.Char), field.New("email_to", field.Char), field.New("email_cc", field.Char), field.New("reply_to", field.Char), field.New("subject", field.Char), field.New("body_html", field.Text), field.New("state", field.Selection), field.New("failure_reason", field.Text), field.New("failure_type", field.Selection), field.New("scheduled_date", field.DateTime), field.New("retry_count", field.Int), field.New("max_retries", field.Int), field.New("auto_delete", field.Bool), field.New("message_id", field.Char), field.New("references", field.Char), field.New("headers", field.Text), field.New("is_notification", field.Bool), field.New("fetchmail_server_id", field.Many2One).WithRelation("fetchmail.server"), field.New("mailing_id", field.Many2One).WithRelation("mailing.mailing"), field.New("mailing_trace_ids", field.One2Many).WithRelation("mailing.trace").WithRelationField("mail_mail_id"))),
		withLogAccess(simple("mail.notification", "mail_notification", field.New("mail_message_id", field.Many2One).WithRelation("mail.message"), field.New("mail_mail_id", field.Many2One).WithRelation("mail.mail"), field.New("res_partner_id", field.Many2One).WithRelation("res.partner"), field.New("mail_email_address", field.Char), field.New("notification_type", field.Selection), field.New("notification_status", field.Selection), field.New("failure_type", field.Selection), field.New("failure_reason", field.Text), field.New("is_read", field.Bool), field.New("read_date", field.DateTime), field.New("author_id", field.Many2One).WithRelation("res.partner"), field.New("sms_id", field.Many2One).WithRelation("sms.sms"), field.New("sms_id_int", field.Int), field.New("sms_tracker_ids", field.One2Many).WithRelation("sms.tracker").WithRelationField("mail_notification_id"), field.New("sms_number", field.Char))),
		simple("mail.followers", "mail_followers", field.New("res_model", field.Char), field.New("res_id", field.Int), field.New("partner_id", field.Many2One).WithRelation("res.partner"), field.New("subtype_ids", field.Many2Many).WithRelation("mail.message.subtype")),
		simple("mail.activity", "mail_activity", field.New("activity_type_id", field.Many2One).WithRelation("mail.activity.type"), field.New("activity_category", field.Selection), field.New("recommended_activity_type_id", field.Many2One).WithRelation("mail.activity.type"), field.New("previous_activity_type_id", field.Many2One).WithRelation("mail.activity.type"), field.New("has_recommended_activities", field.Bool), field.New("chaining_type", field.Selection), field.New("res_model", field.Char), field.New("res_id", field.Int), field.New("user_id", field.Many2One).WithRelation("res.users"), field.New("date_deadline", field.Date), field.New("summary", field.Char), field.New("note", field.Text), field.New("state", field.Selection), field.New("automated", field.Bool), field.New("hide_in_chatter", field.Bool), field.New("attachment_ids", field.Many2Many).WithRelation("ir.attachment"), field.New("active", field.Bool), field.New("date_done", field.DateTime), field.New("feedback", field.Text)),
		simple("mail.activity.type", "mail_activity_type", field.New("name", field.Char), field.New("summary", field.Char), field.New("res_model", field.Char), field.New("category", field.Selection), field.New("default_note", field.Text), field.New("default_user_id", field.Many2One).WithRelation("res.users"), field.New("delay_count", field.Int), field.New("delay_unit", field.Selection), field.New("delay_from", field.Selection), field.New("chaining_type", field.Selection), field.New("triggered_next_type_id", field.Many2One).WithRelation("mail.activity.type"), field.New("suggested_next_type_ids", field.Many2Many).WithRelation("mail.activity.type"), field.New("previous_type_ids", field.Many2Many).WithRelation("mail.activity.type"), field.New("mail_template_ids", field.Many2Many).WithRelation("mail.template"), field.New("icon", field.Char), field.New("active", field.Bool)),
		abstract("mail.composer.mixin", field.New("subject", field.Char), field.New("body", field.Text), field.New("body_html", field.Text), field.New("attachment_ids", field.Many2Many).WithRelation("ir.attachment"), field.New("partner_ids", field.Many2Many).WithRelation("res.partner")),
		composeMessageModel(),
		simple("mail.scheduled.message", "mail_scheduled_message", field.New("mail_message_id", field.Many2One).WithRelation("mail.message"), field.New("mail_mail_id", field.Many2One).WithRelation("mail.mail"), field.New("mail_template_id", field.Many2One).WithRelation("mail.template"), field.New("model", field.Char), field.New("res_id", field.Int), field.New("scheduled_date", field.DateTime), field.New("author_id", field.Many2One).WithRelation("res.partner"), field.New("subject", field.Char), field.New("body", field.Text), field.New("partner_ids", field.Many2Many).WithRelation("res.partner"), field.New("attachment_ids", field.Many2Many).WithRelation("ir.attachment"), field.New("composition_comment_option", field.Selection), field.New("is_note", field.Bool), field.New("notification_parameters", field.Text), field.New("send_context", field.Text), field.New("state", field.Selection)),
		withLogAccess(simple("mail.canned.response", "mail_canned_response", field.New("source", field.Char), field.New("substitution", field.Text), field.New("last_used", field.DateTime), field.New("group_ids", field.Many2Many).WithRelation("res.groups"), field.New("is_shared", field.Bool), field.New("is_editable", field.Bool))),
		simple("mail.template", "mail_template", field.New("name", field.Char), field.New("model", field.Char), field.New("model_id", field.Many2One).WithRelation("ir.model"), field.New("subject", field.Char), field.New("body_html", field.Text), field.New("email_from", field.Char), field.New("email_to", field.Char), field.New("email_cc", field.Char), field.New("reply_to", field.Char), field.New("partner_to", field.Char), field.New("attachment_ids", field.Many2Many).WithRelation("ir.attachment"), field.New("report_template_ids", field.Many2Many).WithRelation("ir.actions.report"), field.New("mail_server_id", field.Many2One).WithRelation("ir.mail_server"), field.New("auto_delete", field.Bool), field.New("scheduled_date", field.DateTime), field.New("active", field.Bool)),
		simple("mail.alias", "mail_alias", field.New("alias_name", field.Char), field.New("model_name", field.Char), field.New("alias_model_id", field.Many2One).WithRelation("ir.model"), field.New("alias_defaults", field.Text), field.New("alias_force_thread_id", field.Int), field.New("alias_parent_model_id", field.Many2One).WithRelation("ir.model"), field.New("alias_parent_thread_id", field.Int), field.New("alias_contact", field.Selection), field.New("alias_incoming_local", field.Bool), field.New("alias_bounced_content", field.Text), field.New("alias_status", field.Selection), field.New("alias_user_id", field.Many2One).WithRelation("res.users"), field.New("alias_domain_id", field.Many2One).WithRelation("mail.alias.domain"), field.New("alias_domain", field.Char), field.New("alias_full_name", field.Char), field.New("active", field.Bool)),
		simple("mail.alias.domain", "mail_alias_domain", field.New("name", field.Char), field.New("company_ids", field.One2Many).WithRelation("res.company").WithRelationField("alias_domain_id"), field.New("sequence", field.Int), field.New("bounce_alias", field.Char), field.New("bounce_email", field.Char), field.New("catchall_alias", field.Char), field.New("catchall_email", field.Char), field.New("default_from", field.Char), field.New("default_from_email", field.Char)),
		simple("mail.gateway.allowed", "mail_gateway_allowed", field.New("email", field.Char), field.New("email_normalized", field.Char)),
		withLogAccess(simple("mail.blacklist", "mail_blacklist", field.New("email", field.Char), field.New("active", field.Bool), field.New("message", field.Text))),
		withLogAccess(simple("phone.blacklist", "phone_blacklist", field.New("number", field.Char), field.New("active", field.Bool), field.New("message", field.Text))),
		simple("utm.campaign", "utm_campaign", field.New("name", field.Char), field.New("mailing_mail_ids", field.One2Many).WithRelation("mailing.mailing").WithRelationField("campaign_id"), field.New("mailing_mail_count", field.Int), field.New("ab_testing_mailings_count", field.Int), field.New("ab_testing_completed", field.Bool), field.New("ab_testing_winner_mailing_id", field.Many2One).WithRelation("mailing.mailing"), field.New("ab_testing_schedule_datetime", field.DateTime), field.New("ab_testing_winner_selection", field.Selection)),
		simple("utm.source", "utm_source", field.New("name", field.Char)),
		simple("utm.medium", "utm_medium", field.New("name", field.Char)),
		withLogAccess(simple("mailing.contact", "mailing_contact", field.New("name", field.Char), field.New("first_name", field.Char), field.New("last_name", field.Char), field.New("company_name", field.Char), field.New("email", field.Char), field.New("email_normalized", field.Char), field.New("phone", field.Char), field.New("phone_sanitized", field.Char), field.New("active", field.Bool), field.New("list_ids", field.Many2Many).WithRelation("mailing.list"), field.New("subscription_ids", field.One2Many).WithRelation("mailing.subscription").WithRelationField("contact_id"))),
		withLogAccess(simple("mailing.list", "mailing_list", field.New("name", field.Char), field.New("active", field.Bool), field.New("is_public", field.Bool), field.New("contact_ids", field.Many2Many).WithRelation("mailing.contact"), field.New("subscription_ids", field.One2Many).WithRelation("mailing.subscription").WithRelationField("list_id"))),
		withLogAccess(simple("mailing.subscription", "mailing_subscription", field.New("contact_id", field.Many2One).WithRelation("mailing.contact"), field.New("list_id", field.Many2One).WithRelation("mailing.list"), field.New("opt_out", field.Bool), field.New("opt_out_reason_id", field.Many2One).WithRelation("mailing.subscription.optout"), field.New("opt_out_datetime", field.DateTime))),
		simple("mailing.subscription.optout", "mailing_subscription_optout", field.New("name", field.Char), field.New("sequence", field.Int), field.New("active", field.Bool)),
		withLogAccess(simple("mailing.mailing", "mailing_mailing", field.New("name", field.Char), field.New("subject", field.Char), field.New("preview", field.Char), field.New("body_html", field.Text), field.New("email_from", field.Char), field.New("reply_to", field.Char), field.New("reply_to_mode", field.Selection), field.New("mail_server_id", field.Many2One).WithRelation("ir.mail_server"), field.New("attachment_ids", field.Many2Many).WithRelation("ir.attachment"), field.New("keep_archives", field.Bool), field.New("state", field.Selection), field.New("sent_date", field.DateTime), field.New("schedule_type", field.Selection), field.New("schedule_date", field.DateTime), field.New("kpi_mail_required", field.Bool), field.New("user_id", field.Many2One).WithRelation("res.users"), field.New("mailing_model_real", field.Char), field.New("mailing_domain", field.Char), field.New("mailing_on_mailing_list", field.Bool), field.New("use_exclusion_list", field.Bool), field.New("sms_allow_unsubscribe", field.Bool), field.New("contact_list_ids", field.Many2Many).WithRelation("mailing.list"), field.New("campaign_id", field.Many2One).WithRelation("utm.campaign"), field.New("source_id", field.Many2One).WithRelation("utm.source"), field.New("medium_id", field.Many2One).WithRelation("utm.medium"), field.New("ab_testing_enabled", field.Bool), field.New("ab_testing_pc", field.Int), field.New("ab_testing_is_winner_mailing", field.Bool), field.New("ab_testing_mailings_count", field.Int), field.New("ab_testing_completed", field.Bool), field.New("ab_testing_schedule_datetime", field.DateTime), field.New("ab_testing_winner_selection", field.Selection), field.New("is_ab_test_sent", field.Bool), field.New("total", field.Int), field.New("scheduled", field.Int), field.New("expected", field.Int), field.New("canceled", field.Int), field.New("sent", field.Int), field.New("process", field.Int), field.New("pending", field.Int), field.New("delivered", field.Int), field.New("opened", field.Int), field.New("clicked", field.Int), field.New("replied", field.Int), field.New("bounced", field.Int), field.New("failed", field.Int), field.New("received_ratio", field.Float), field.New("opened_ratio", field.Float), field.New("replied_ratio", field.Float), field.New("bounced_ratio", field.Float), field.New("clicks_ratio", field.Float), field.New("link_trackers_count", field.Int), field.New("mailing_trace_ids", field.One2Many).WithRelation("mailing.trace").WithRelationField("mass_mailing_id"))),
		simple("mailing.mailing.test", "mailing_mailing_test", field.New("email_to", field.Text), field.New("mass_mailing_id", field.Many2One).WithRelation("mailing.mailing")),
		simple("mailing.mailing.schedule.date", "mailing_mailing_schedule_date", field.New("schedule_date", field.DateTime), field.New("mass_mailing_id", field.Many2One).WithRelation("mailing.mailing")),
		withLogAccess(simple("link.tracker", "link_tracker", field.New("url", field.Char), field.New("absolute_url", field.Char), field.New("short_url", field.Char), field.New("redirected_url", field.Char), field.New("short_url_host", field.Char), field.New("title", field.Char), field.New("label", field.Char), field.New("link_code_ids", field.One2Many).WithRelation("link.tracker.code").WithRelationField("link_id"), field.New("code", field.Char), field.New("link_click_ids", field.One2Many).WithRelation("link.tracker.click").WithRelationField("link_id"), field.New("count", field.Int), field.New("campaign_id", field.Many2One).WithRelation("utm.campaign"), field.New("medium_id", field.Many2One).WithRelation("utm.medium"), field.New("source_id", field.Many2One).WithRelation("utm.source"), field.New("mass_mailing_id", field.Many2One).WithRelation("mailing.mailing"))),
		simple("link.tracker.code", "link_tracker_code", field.New("code", field.Char), field.New("link_id", field.Many2One).WithRelation("link.tracker")),
		withLogAccess(simple("link.tracker.click", "link_tracker_click", field.New("campaign_id", field.Many2One).WithRelation("utm.campaign"), field.New("link_id", field.Many2One).WithRelation("link.tracker"), field.New("ip", field.Char), field.New("country_id", field.Many2One).WithRelation("res.country"), field.New("mailing_trace_id", field.Many2One).WithRelation("mailing.trace"), field.New("mass_mailing_id", field.Many2One).WithRelation("mailing.mailing"), field.New("whatsapp_message_id", field.Many2One).WithRelation("whatsapp.message"))),
		withLogAccess(simple("sms.template", "sms_template", field.New("name", field.Char), field.New("model_id", field.Many2One).WithRelation("ir.model"), field.New("model", field.Char), field.New("body", field.Char), field.New("sidebar_action_id", field.Many2One).WithRelation("ir.actions.act_window"))),
		withLogAccess(simple("sms.composer", "sms_composer", field.New("composition_mode", field.Selection), field.New("res_model", field.Char), field.New("res_model_description", field.Char), field.New("res_id", field.Int), field.New("res_ids", field.Char), field.New("res_ids_count", field.Int), field.New("comment_single_recipient", field.Bool), field.New("mass_keep_log", field.Bool), field.New("mass_force_send", field.Bool), field.New("use_exclusion_list", field.Bool), field.New("recipient_valid_count", field.Int), field.New("recipient_invalid_count", field.Int), field.New("recipient_single_description", field.Text), field.New("recipient_single_number", field.Char), field.New("recipient_single_number_itf", field.Char), field.New("recipient_single_valid", field.Bool), field.New("number_field_name", field.Char), field.New("numbers", field.Char), field.New("sanitized_numbers", field.Char), field.New("template_id", field.Many2One).WithRelation("sms.template"), field.New("body", field.Text))),
		withLogAccess(simple("sms.sms", "sms_sms", field.New("uuid", field.Char), field.New("number", field.Char), field.New("body", field.Text), field.New("partner_id", field.Many2One).WithRelation("res.partner"), field.New("mail_message_id", field.Many2One).WithRelation("mail.message"), field.New("state", field.Selection), field.New("failure_type", field.Selection), field.New("to_delete", field.Bool), field.New("mailing_id", field.Many2One).WithRelation("mailing.mailing"), field.New("mailing_trace_ids", field.One2Many).WithRelation("mailing.trace").WithRelationField("sms_id_int"))),
		withLogAccess(simple("sms.tracker", "sms_tracker", field.New("sms_uuid", field.Char), field.New("mail_notification_id", field.Many2One).WithRelation("mail.notification"), field.New("mailing_trace_id", field.Many2One).WithRelation("mailing.trace"))),
		withLogAccess(simple("mailing.trace", "mailing_trace", field.New("trace_type", field.Selection), field.New("is_test_trace", field.Bool), field.New("mail_mail_id", field.Many2One).WithRelation("mail.mail"), field.New("mail_mail_id_int", field.Int), field.New("email", field.Char), field.New("message_id", field.Char), field.New("medium_id", field.Many2One).WithRelation("utm.medium"), field.New("source_id", field.Many2One).WithRelation("utm.source"), field.New("model", field.Char), field.New("res_id", field.Int), field.New("mass_mailing_id", field.Many2One).WithRelation("mailing.mailing"), field.New("campaign_id", field.Many2One).WithRelation("utm.campaign"), field.New("sent_datetime", field.DateTime), field.New("open_datetime", field.DateTime), field.New("reply_datetime", field.DateTime), field.New("trace_status", field.Selection), field.New("failure_type", field.Selection), field.New("failure_reason", field.Text), field.New("links_click_datetime", field.DateTime), field.New("sms_id", field.Many2One).WithRelation("sms.sms"), field.New("sms_id_int", field.Int), field.New("sms_tracker_ids", field.One2Many).WithRelation("sms.tracker").WithRelationField("mailing_trace_id"), field.New("sms_number", field.Char), field.New("sms_code", field.Char))),
		withLogAccess(simple("marketing.campaign", "marketing_campaign", field.New("name", field.Char), field.New("utm_campaign_id", field.Many2One).WithRelation("utm.campaign"), field.New("state", field.Selection))),
		withLogAccess(simple("marketing.activity", "marketing_activity", field.New("name", field.Char), field.New("activity_type", field.Selection), field.New("campaign_id", field.Many2One).WithRelation("marketing.campaign"), field.New("whatsapp_template_id", field.Many2One).WithRelation("whatsapp.template"), field.New("server_action_id", field.Many2One).WithRelation("ir.actions.server"), field.New("interval_number", field.Int), field.New("interval_type", field.Selection), field.New("trigger_type", field.Selection), field.New("trigger_category", field.Selection), field.New("whatsapp_error", field.Bool))),
		withLogAccess(simple("whatsapp.account", "whatsapp_account", field.New("name", field.Char), field.New("active", field.Bool), field.New("app_uid", field.Char), field.New("account_uid", field.Char), field.New("phone_uid", field.Char), field.New("phone_number", field.Char), field.New("token", field.Char).WithGroups("base.group_system"), field.New("app_secret", field.Char).WithGroups("base.group_system"), field.New("webhook_verify_token", field.Char), field.New("callback_url", field.Char), field.New("debug_logging", field.Bool), field.New("templates_count", field.Int))),
		withLogAccess(simple("whatsapp.template", "whatsapp_template", field.New("name", field.Char), field.New("template_name", field.Char), field.New("active", field.Bool), field.New("wa_template_uid", field.Char), field.New("wa_account_id", field.Many2One).WithRelation("whatsapp.account"), field.New("model_id", field.Many2One).WithRelation("ir.model"), field.New("model", field.Char), field.New("phone_field", field.Char), field.New("lang_code", field.Selection), field.New("template_type", field.Selection), field.New("status", field.Selection), field.New("quality", field.Selection), field.New("header_type", field.Selection), field.New("header_text", field.Char), field.New("header_attachment_ids", field.Many2Many).WithRelation("ir.attachment"), field.New("footer_text", field.Char), field.New("body", field.Text), field.New("variable_ids", field.One2Many).WithRelation("whatsapp.template.variable").WithRelationField("wa_template_id"), field.New("button_ids", field.One2Many).WithRelation("whatsapp.template.button").WithRelationField("wa_template_id"))),
		withLogAccess(simple("whatsapp.template.button", "whatsapp_template_button", field.New("name", field.Char), field.New("text", field.Char), field.New("template_id", field.Many2One).WithRelation("whatsapp.template"), field.New("wa_template_id", field.Many2One).WithRelation("whatsapp.template"), field.New("sequence", field.Int), field.New("button_type", field.Selection), field.New("url_type", field.Selection), field.New("website_url", field.Char), field.New("dynamic_url", field.Char), field.New("call_number", field.Char), field.New("variable_ids", field.One2Many).WithRelation("whatsapp.template.variable").WithRelationField("button_id"))),
		withLogAccess(simple("whatsapp.template.variable", "whatsapp_template_variable", field.New("name", field.Char), field.New("button_id", field.Many2One).WithRelation("whatsapp.template.button"), field.New("wa_template_id", field.Many2One).WithRelation("whatsapp.template"), field.New("model", field.Char), field.New("line_type", field.Selection), field.New("field_type", field.Selection), field.New("field_name", field.Char), field.New("demo_value", field.Char))),
		withLogAccess(simple("whatsapp.message", "whatsapp_message", field.New("mobile_number", field.Char), field.New("mobile_number_formatted", field.Char), field.New("message_type", field.Selection), field.New("state", field.Selection), field.New("failure_type", field.Selection), field.New("failure_reason", field.Char), field.New("template_id", field.Many2One).WithRelation("whatsapp.template"), field.New("wa_template_id", field.Many2One).WithRelation("whatsapp.template"), field.New("msg_uid", field.Char), field.New("wa_account_id", field.Many2One).WithRelation("whatsapp.account"), field.New("parent_id", field.Many2One).WithRelation("whatsapp.message"), field.New("mail_message_id", field.Many2One).WithRelation("mail.message"), field.New("model", field.Char), field.New("res_id", field.Int), field.New("body", field.Text), field.New("components", field.Text), field.New("free_text_json", field.Text), field.New("links_click_datetime", field.DateTime), field.New("marketing_trace_ids", field.One2Many).WithRelation("marketing.trace").WithRelationField("whatsapp_message_id"))),
		withLogAccess(simple("marketing.trace", "marketing_trace", field.New("activity_id", field.Many2One).WithRelation("marketing.activity"), field.New("whatsapp_message_id", field.Many2One).WithRelation("whatsapp.message"), field.New("links_click_datetime", field.DateTime), field.New("state", field.Selection), field.New("schedule_date", field.DateTime), field.New("state_msg", field.Text), field.New("parent_id", field.Many2One).WithRelation("marketing.trace"), field.New("child_ids", field.One2Many).WithRelation("marketing.trace").WithRelationField("parent_id"))),
		simple("mail.message.subtype", "mail_message_subtype", field.New("name", field.Char), field.New("description", field.Text), field.New("res_model", field.Char), field.New("default", field.Bool), field.New("internal", field.Bool)),
		simple("fetchmail.server", "fetchmail_server", field.New("name", field.Char), field.New("active", field.Bool), field.New("state", field.Selection), field.New("server", field.Char), field.New("port", field.Int), field.New("server_type", field.Selection), field.New("server_type_info", field.Text), field.New("is_ssl", field.Bool), field.New("attach", field.Bool), field.New("original", field.Bool), field.New("date", field.DateTime), field.New("error_date", field.DateTime), field.New("error_message", field.Text), field.New("user", field.Char), field.New("password", field.Char).WithGroups("base.group_system"), field.New("object_id", field.Many2One).WithRelation("ir.model"), field.New("priority", field.Int), field.New("message_ids", field.One2Many).WithRelation("mail.mail").WithRelationField("fetchmail_server_id"), field.New("configuration", field.Text), field.New("script", field.Char)),
		simple("discuss.channel",
			"discuss_channel",
			field.New("name", field.Char),
			field.New("channel_type", field.Selection),
			field.New("active", field.Bool),
			field.New("group_public_id", field.Many2One).WithRelation("res.groups"),
			field.New("ai_env_context", field.Text),
			field.New("ai_agent_id", field.Many2One).WithRelation("ai.agent"),
		),
		simple("discuss.channel.member", "discuss_channel_member", field.New("channel_id", field.Many2One).WithRelation("discuss.channel"), field.New("partner_id", field.Many2One).WithRelation("res.partner"), field.New("user_id", field.Many2One).WithRelation("res.users"), field.New("guest_id", field.Many2One).WithRelation("mail.guest"), field.New("last_seen_dt", field.DateTime)),
		simple("mail.guest", "mail_guest", field.New("name", field.Char), field.New("email", field.Char), field.New("access_token", field.Char), field.New("country_id", field.Many2One).WithRelation("res.country"), field.New("lang", field.Char), field.New("timezone", field.Char)),
		simple("mail.presence", "mail_presence", field.New("user_id", field.Many2One).WithRelation("res.users"), field.New("guest_id", field.Many2One).WithRelation("mail.guest"), field.New("status", field.Selection), field.New("last_poll", field.DateTime)),
	}
}

func simple(name, table string, fields ...field.Field) model.Model {
	m := model.New(name, table)
	for _, f := range fields {
		m.AddField(f)
	}
	return m
}

func withLogAccess(m model.Model) model.Model {
	for _, f := range []field.Field{
		field.New("create_uid", field.Many2One).WithRelation("res.users"),
		field.New("create_date", field.DateTime),
		field.New("write_uid", field.Many2One).WithRelation("res.users"),
		field.New("write_date", field.DateTime),
	} {
		if _, exists := m.Fields[f.Name]; !exists {
			m.AddField(f)
		}
	}
	return m
}

func abstract(name string, fields ...field.Field) model.Model {
	m := model.New(name, "")
	m.Abstract = true
	for _, f := range fields {
		m.AddField(f)
	}
	return m
}

func withInherit(m model.Model, inherited ...string) model.Model {
	m.Inherit = append(m.Inherit, inherited...)
	return m
}

func embeddedActionsModel() model.Model {
	m := model.New("ir.embedded.actions", "ir_embedded_actions")
	m.Order = "sequence,id"
	for _, f := range []field.Field{
		field.New("name", field.Char),
		field.New("sequence", field.Int),
		field.New("parent_action_id", field.Many2One).WithRelation("ir.actions.act_window"),
		field.New("parent_res_id", field.Int),
		field.New("parent_res_model", field.Char),
		field.New("action_id", field.Many2One).WithRelation("ir.actions.actions"),
		field.New("python_method", field.Char),
		field.New("user_id", field.Many2One).WithRelation("res.users"),
		field.New("is_deletable", field.Bool),
		field.New("default_view_mode", field.Char),
		field.New("filter_ids", field.One2Many).WithRelation("ir.filters").WithRelationField("embedded_action_id"),
		field.New("is_visible", field.Bool),
		field.New("domain", field.Char),
		field.New("context", field.Char),
		field.New("groups_ids", field.Many2Many).WithRelation("res.groups"),
	} {
		m.AddField(f)
	}
	return m
}

func reportPaperformatModel() model.Model {
	m := model.New("report.paperformat", "report_paperformat")
	for _, f := range []field.Field{
		field.New("name", field.Char),
		field.New("default", field.Bool),
		field.New("format", field.Selection),
		field.New("page_height", field.Float),
		field.New("page_width", field.Float),
		field.New("orientation", field.Selection),
		field.New("margin_top", field.Float),
		field.New("margin_bottom", field.Float),
		field.New("margin_left", field.Float),
		field.New("margin_right", field.Float),
		field.New("header_line", field.Bool),
		field.New("header_spacing", field.Float),
		field.New("dpi", field.Int),
		field.New("css_margins", field.Bool),
		field.New("disable_shrinking", field.Bool),
	} {
		m.AddField(f)
	}
	return m
}

func serverActionHistoryWizardModel() model.Model {
	m := model.New("server.action.history.wizard", "server_action_history_wizard")
	m.Transient = true
	for _, f := range []field.Field{
		field.New("action_id", field.Many2One).WithRelation("ir.actions.server"),
		field.New("code_diff", field.Text),
		field.New("current_code", field.Text),
		field.New("revision", field.Many2One).WithRelation("ir.actions.server.history"),
	} {
		m.AddField(f)
	}
	return m
}

func composeMessageModel() model.Model {
	m := model.New("mail.compose.message", "mail_compose_message")
	m.Transient = true
	for _, f := range []field.Field{
		field.New("composition_mode", field.Selection),
		field.New("composition_comment_option", field.Selection),
		field.New("message_type", field.Selection),
		field.New("subtype_is_log", field.Bool),
		field.New("model", field.Char),
		field.New("res_id", field.Int),
		field.New("res_ids", field.Many2Many),
		field.New("template_id", field.Many2One).WithRelation("mail.template"),
		field.New("subject", field.Char),
		field.New("body", field.Text),
		field.New("body_html", field.Text),
		field.New("email_from", field.Char),
		field.New("email_to", field.Char),
		field.New("email_cc", field.Char),
		field.New("reply_to", field.Char),
		field.New("partner_ids", field.Many2Many).WithRelation("res.partner"),
		field.New("attachment_ids", field.Many2Many).WithRelation("ir.attachment"),
		field.New("parent_id", field.Many2One).WithRelation("mail.message"),
		field.New("subtype_id", field.Many2One).WithRelation("mail.message.subtype"),
		field.New("scheduled_date", field.DateTime),
		field.New("mail_server_id", field.Many2One),
		field.New("author_id", field.Many2One).WithRelation("res.partner"),
		field.New("auto_delete", field.Bool),
		field.New("mass_mailing_id", field.Many2One).WithRelation("mailing.mailing"),
		field.New("use_exclusion_list", field.Bool),
		field.New("notify", field.Bool),
		field.New("body_is_html", field.Bool),
	} {
		m.AddField(f)
	}
	return m
}

func resConfigSettingsModel() model.Model {
	m := model.New("res.config.settings", "res_config_settings")
	m.Transient = true
	for _, f := range []field.Field{
		field.New("company_id", field.Many2One).WithRelation("res.company"),
		field.New("is_root_company", field.Bool),
		field.New("module_base_import", field.Bool),
		field.New("module_google_calendar", field.Bool),
		field.New("module_microsoft_calendar", field.Bool),
		field.New("module_mail_plugin", field.Bool),
		field.New("module_auth_oauth", field.Bool),
		field.New("module_auth_ldap", field.Bool),
		field.New("module_account_inter_company_rules", field.Bool),
		field.New("module_voip", field.Bool),
		field.New("module_web_unsplash", field.Bool),
		field.New("module_sms", field.Bool),
		field.New("module_partner_autocomplete", field.Bool),
		field.New("module_base_geolocalize", field.Bool),
		field.New("module_google_recaptcha", field.Bool),
		field.New("module_website_cf_turnstile", field.Bool),
		field.New("module_google_address_autocomplete", field.Bool),
		field.New("report_footer", field.Text),
		field.New("group_multi_currency", field.Bool),
		field.New("external_report_layout_id", field.Many2One).WithRelation("ir.ui.view"),
		field.New("show_effect", field.Bool),
		field.New("company_count", field.Int),
		field.New("active_user_count", field.Int),
		field.New("language_count", field.Int),
		field.New("company_name", field.Char),
		field.New("company_informations", field.Text),
		field.New("company_country_code", field.Char),
		field.New("company_country_group_codes", field.Text),
		field.New("profiling_enabled_until", field.DateTime),
		field.New("has_accounting_entries", field.Bool),
		field.New("currency_id", field.Many2One).WithRelation("res.currency"),
		field.New("has_chart_of_accounts", field.Bool),
		field.New("chart_template", field.Selection),
		field.New("sale_tax_id", field.Many2One).WithRelation("account.tax"),
		field.New("purchase_tax_id", field.Many2One).WithRelation("account.tax"),
		field.New("account_price_include", field.Selection),
		field.New("tax_calculation_rounding_method", field.Selection),
		field.New("module_account_accountant", field.Bool),
		field.New("group_cash_rounding", field.Bool),
		field.New("show_sale_receipts", field.Bool),
		field.New("module_account_budget", field.Bool),
		field.New("module_account_payment", field.Bool),
		field.New("module_account_reports", field.Bool),
		field.New("module_account_check_printing", field.Bool),
		field.New("module_account_batch_payment", field.Bool),
		field.New("module_currency_rate_live", field.Bool),
		field.New("module_product_margin", field.Bool),
		field.New("tax_exigibility", field.Bool),
		field.New("use_invoice_terms", field.Bool),
		field.New("terms_type", field.Selection),
		field.New("invoice_terms", field.Text),
		field.New("invoice_terms_html", field.Text),
		field.New("preview_ready", field.Bool),
		field.New("group_sale_delivery_address", field.Bool),
		field.New("group_uom", field.Bool),
		field.New("group_analytic_accounting", field.Bool),
		field.New("digest_emails", field.Bool),
		field.New("digest_id", field.Many2One).WithRelation("digest.digest"),
		field.New("portal_allow_api_keys", field.Bool),
		field.New("country_code", field.Char),
		field.New("income_account_id", field.Many2One).WithRelation("account.account"),
		field.New("expense_account_id", field.Many2One).WithRelation("account.account"),
		field.New("account_fiscal_country_id", field.Many2One).WithRelation("res.country"),
	} {
		m.AddField(f)
	}
	return m
}

func serverActionStateField() field.Field {
	return selectionField("state",
		field.SelectionOption{Value: "code", Label: "Execute Code"},
		field.SelectionOption{Value: "object_create", Label: "Create Record"},
		field.SelectionOption{Value: "object_write", Label: "Update Record"},
		field.SelectionOption{Value: "multi", Label: "Multi Actions"},
		field.SelectionOption{Value: "mail_post", Label: "Send Email"},
		field.SelectionOption{Value: "followers", Label: "Add Followers"},
		field.SelectionOption{Value: "remove_followers", Label: "Remove Followers"},
		field.SelectionOption{Value: "next_activity", Label: "Create Next Activity"},
		field.SelectionOption{Value: "sms", Label: "Send SMS"},
		field.SelectionOption{Value: "whatsapp", Label: "Send WhatsApp"},
		field.SelectionOption{Value: "webhook", Label: "Webhook"},
		field.SelectionOption{Value: "ai", Label: "AI Action"},
		field.SelectionOption{Value: "documents_account_record_create", Label: "Create Vendor Bill"},
	)
}

func selectionField(name string, options ...field.SelectionOption) field.Field {
	f := field.New(name, field.Selection)
	f.Selection = append([]field.SelectionOption(nil), options...)
	return f
}
